In [2]:
import os
import numpy as np
import pandas as pd
import pandas_profiling
import plotnine
from plotnine import *  # Provides a ggplot-like interface to matplotlib.
from IPython.display import display

## Plot setup.
theme_set(theme_bw(base_size = 11)) # Default theme for plots.

def get_boxplot_fun_data(df):
  """Returns a data frame with a y position and a label, for use annotating ggplot boxplots.

  Args:
    d: A data frame.
  Returns:
    A data frame with column y as max and column label as length.
  """
  d = {'y': max(df), 'label': f'N = {len(df)}'}
  return(pd.DataFrame(data=d, index=[0]))

# NOTE: if you get any errors from this cell, restart your kernel and run it again.

In [27]:
import pandas
import os

# This query represents dataset "Asthma_exacerb_predict" for domain "person" and was generated for All of Us Registered Tier Dataset v4
dataset_64469718_person_sql = """
    SELECT
        person.BIRTH_DATETIME as DATE_OF_BIRTH,
        person.PERSON_ID,
        p_race_concept.concept_name as RACE,
        p_gender_concept.concept_name as GENDER,
        p_ethnicity_concept.concept_name as ETHNICITY,
        p_sex_at_birth_concept.concept_name as SEX_AT_BIRTH 
    FROM
        `""" + os.environ["WORKSPACE_CDR"] + """.person` person 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_race_concept 
            on person.race_concept_id = p_race_concept.CONCEPT_ID 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_gender_concept 
            on person.gender_concept_id = p_gender_concept.CONCEPT_ID 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_ethnicity_concept 
            on person.ethnicity_concept_id = p_ethnicity_concept.CONCEPT_ID 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_sex_at_birth_concept 
            on person.sex_at_birth_concept_id = p_sex_at_birth_concept.CONCEPT_ID  
    WHERE
        person.PERSON_ID IN (
            select
                person_id  
            from
                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
            where
                cb_search_person.person_id in (
                    select
                        criteria.person_id 
                    from
                        (select
                            distinct person_id,
                            entry_date,
                            concept_id 
                        from
                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                        where
                            person_id in (
                                select
                                    person_id 
                                from
                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                where
                                    is_standard = 1 
                                    and concept_id in (
                                        select
                                            distinct c.concept_id 
                                        from
                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                        join
                                            (
                                                select
                                                    cast(cr.id as string) as id 
                                                from
                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                where
                                                    domain_id = 'CONDITION' 
                                                    and is_standard = 1 
                                                    and concept_id in (764949, 46274062, 4271333, 46270573, 4146581, 46273487, 46270028, 45768963, 42539549, 46269770, 4142738, 45768910, 443801, 4145356, 4152913, 45769350, 46273454, 4279553, 45769443, 317009, 314754, 4138760, 252946, 46269783, 46269790, 252658, 46269786, 45768965, 4051466, 46273462, 4245676, 252942, 4215802, 45772937, 40481763, 37108581, 4075237, 256448, 46269802, 4141978, 764677, 46270322, 4125022, 46269776, 45768964, 4233784, 4155468, 37310241, 46273635, 4207479, 4123253, 45769352, 4143828, 42535716, 257581, 46273452, 45771045, 46269778, 312950, 45769351, 4309833, 45768911, 36684328, 4308356, 313236, 46269789, 45768912, 761844, 42536208, 4145497, 4312524, 46270030, 46269787, 40483397, 45769438, 45769441, 43530693, 45773005, 4206340, 45766728, 4194289, 46270082, 45769442, 42538744, 4191479, 46269784, 4155469, 37116845) 
                                                    and is_selectable = 1 
                                                    and full_text like '%[condition_rank1]%'
                                            ) a 
                                                on (
                                                    c.path like concat('%.',
                                                a.id,
                                                '.%') 
                                                or c.path like concat('%.',
                                                a.id) 
                                                or c.path like concat(a.id,
                                                '.%')) 
                                            where
                                                domain_id = 'CONDITION' 
                                                and is_standard = 1 
                                                and is_selectable = 1
                                            )
                                        union
                                        all select
                                            person_id 
                                        from
                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                        where
                                            is_standard = 0 
                                            and concept_id in (
                                                select
                                                    distinct c.concept_id 
                                                from
                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                join
                                                    (
                                                        select
                                                            cast(cr.id as string) as id 
                                                        from
                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                        where
                                                            domain_id = 'CONDITION' 
                                                            and is_standard = 0 
                                                            and concept_id in (46270322, 4155468, 46269789, 45572168, 45768965, 313236, 45768911, 4207479, 46273454, 44820889, 46270573, 44834769, 45601133, 45771045, 46269802, 4194289, 45567266, 44824288, 1569490, 45768912, 44829012, 4215802, 46269784, 44821988, 46270030, 42539549, 312950, 46269786, 764949, 4051466, 4245676, 45543269, 45543270, 45557626, 45769351, 4143828, 4152913, 45769442, 46273635, 45772937, 45548117, 4191479, 44832423, 4125022, 44833611, 45591559, 45576951, 4271333, 317009, 37310241, 4206340, 45548116, 45572170, 45562457, 4146581, 4123253, 256448, 46269776, 45768964, 46269787, 46273452, 44823144, 4312524, 4279553, 43530693, 42535716, 44830115, 46273487, 45769438, 4138760, 4155469, 36684328, 44831280, 1569491, 46269770, 40483397, 1569488, 44831278, 45576952, 45567265, 44824289, 44826679, 4141978, 45601134, 4145356, 43530700, 45773005, 4144757, 45581859, 45769441, 46269778, 4309833, 46269783, 4142738, 44831279, 4308356, 37116845, 44832424, 45581860, 257581, 44828510, 45768963, 764677, 44837136, 252658, 4145497, 46270028, 1569489, 46269790, 46273462, 45766728, 46270082, 44837135, 42536208, 42538744, 45768910, 37108581, 44821987, 35225323, 314754, 45586675, 40410639, 44824287, 761844, 45769352, 4075237, 45591558, 443801, 45572169, 45572171, 46274062, 4233784) 
                                                            and is_selectable = 1 
                                                            and full_text like '%[condition_rank1]%'
                                                    ) a 
                                                        on (
                                                            c.path like concat('%.',
                                                        a.id,
                                                        '.%') 
                                                        or c.path like concat('%.',
                                                        a.id) 
                                                        or c.path like concat(a.id,
                                                        '.%')) 
                                                    where
                                                        domain_id = 'CONDITION' 
                                                        and is_standard = 0 
                                                        and is_selectable = 1
                                                    )
                                            )
                                        ) criteria 
                                ) 
                        )"""

dataset_64469718_person_df = pandas.read_gbq(dataset_64469718_person_sql, dialect="standard", progress_bar_type="tqdm_notebook")

dataset_64469718_person_df.head(5)

HBox(children=(FloatProgress(value=0.0, description='Downloading', max=39330.0, style=ProgressStyle(descriptioâ€¦

,DATE_OF_BIRTH,PERSON_ID,RACE,GENDER,ETHNICITY,SEX_AT_BIRTH
0,1970-12-31 00:00:00+00:00,1222795,None of these,Male,What Race Ethnicity: Race Ethnicity None Of These,No matching concept
1,1950-12-07 00:00:00+00:00,3194246,None of these,Female,What Race Ethnicity: Race Ethnicity None Of These,No matching concept
2,1960-09-03 00:00:00+00:00,1198242,I prefer not to answer,"Not man only, not woman only, prefer not to an...",PMI: Prefer Not To Answer,No matching concept
3,1987-06-22 00:00:00+00:00,1077946,PMI: Skip,"Not man only, not woman only, prefer not to an...",PMI: Skip,No matching concept
4,1950-12-22 00:00:00+00:00,1289088,PMI: Skip,"Not man only, not woman only, prefer not to an...",PMI: Skip,No matching concept

In [28]:
dataset_64469718_person_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39330 entries, 0 to 39329
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE_OF_BIRTH  39330 non-null  datetime64[ns, UTC]
 1   PERSON_ID      39330 non-null  int64
 2   RACE           39330 non-null  object
 3   GENDER         39330 non-null  object
 4   ETHNICITY      39330 non-null  object
 5   SEX_AT_BIRTH   39330 non-null  object
dtypes: datetime64[ns, UTC](1), int64(1), object(4)
memory usage: 1.8+ MB

In [35]:
person_df=dataset_64469718_person_df

In [30]:
#!pip install pyjanitor
import janitor

In [36]:
person_df = janitor.clean_names(person_df)

In [7]:
# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = person_df  

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'person_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
os.system(f"gsutil cp './{destination_filename}' '{my_bucket}/data/'")
print(f'[INFO] {destination_filename} is successfully uploaded in your bucket.')

[INFO] person_df.csv is successfully uploaded in your bucket.

In [8]:
person_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39330 entries, 0 to 39329
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date_of_birth  39330 non-null  datetime64[ns, UTC]
 1   person_id      39330 non-null  int64
 2   race           39330 non-null  object
 3   gender         39330 non-null  object
 4   ethnicity      39330 non-null  object
 5   sex_at_birth   39330 non-null  object
dtypes: datetime64[ns, UTC](1), int64(1), object(4)
memory usage: 1.8+ MB

In [9]:
person_df.duplicated(subset='person_id').value_counts()

False    39330
dtype: int64

In [32]:
import pandas
import os

# This query represents dataset "Asthma_exacerb_predict" for domain "condition" and was generated for All of Us Registered Tier Dataset v4
dataset_64469718_condition_sql = """
    SELECT
        c_occurrence.CONDITION_START_DATETIME,
        c_occurrence.CONDITION_END_DATETIME,
        c_occurrence.STOP_REASON,
        c_occurrence.PERSON_ID,
        c_type.concept_name as CONDITION_TYPE_CONCEPT_NAME,
        c_status.concept_name as CONDITION_STATUS_CONCEPT_NAME,
        c_standard_concept.concept_name as STANDARD_CONCEPT_NAME,
        c_standard_concept.vocabulary_id as STANDARD_VOCABULARY,
        visit.concept_name as VISIT_OCCURRENCE_CONCEPT_NAME 
    from
        ( SELECT
            * 
        from
            `""" + os.environ["WORKSPACE_CDR"] + """.condition_occurrence` c_occurrence 
        WHERE
            (
                condition_concept_id in  (
                    select
                        distinct c.concept_id 
                    from
                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                    join
                        (
                            select
                                cast(cr.id as string) as id 
                            from
                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                            where
                                domain_id = 'CONDITION' 
                                and is_standard = 1 
                                and concept_id in (
                                    42538744, 43530693, 45768910, 46273487, 4138760, 45768911, 46270082, 4146581, 4279553, 312950, 4155469, 45768912, 45769350, 45769441, 4155468, 45769351, 4308356, 257581, 45768963, 45769442, 4233784, 4141978, 4143828, 4142738, 45771045, 45768964, 36684328, 4312524, 45772937, 45768965, 46274062, 443801, 4191479, 317009, 314754, 45769438, 313236, 4145356, 45773005, 4152913, 4145497
                                ) 
                                and is_selectable = 1 
                                and full_text like '%[condition_rank1]%'
                        ) a 
                            on (
                                c.path like concat('%.',
                            a.id,
                            '.%') 
                            or c.path like concat('%.',
                            a.id) 
                            or c.path like concat(a.id,
                            '.%')) 
                        where
                            domain_id = 'CONDITION' 
                            and is_standard = 1 
                            and is_selectable = 1
                        ) 
                        OR  condition_source_concept_id in  (
                            select
                                distinct c.concept_id 
                            from
                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                            join
                                (
                                    select
                                        cast(cr.id as string) as id 
                                    from
                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                    where
                                        domain_id = 'CONDITION' 
                                        and is_standard = 0 
                                        and concept_id in (
                                            1569489, 42538744, 44824289, 4146581, 313236, 44832423, 45768910, 35225323, 1569488, 46273487, 46270082, 4138760, 44828510, 45768911, 44832424, 45586675, 4155469, 44824287, 45769441, 45576951, 45591559, 45572169, 44837136, 45768963, 44824288, 4125022, 4155468, 4308356, 45562457, 45591558, 257581, 45557626, 312950, 45572168, 44833611, 45768964, 45771045, 45567266, 45601133, 4141978, 45572171, 45768965, 45567265, 45601134, 44831280, 44837135, 45772937, 314754, 4191479, 44821987, 1569491, 45548117, 46274062, 4152913, 45581860, 443801, 44820889, 45543270, 1569490, 4145356, 44821988, 4143828, 45581859, 45769438, 44826679, 45548116, 317009, 4145497, 45543269, 44823144
                                        ) 
                                        and is_selectable = 1 
                                        and full_text like '%[condition_rank1]%'
                                ) a 
                                    on (
                                        c.path like concat('%.',
                                    a.id,
                                    '.%') 
                                    or c.path like concat('%.',
                                    a.id) 
                                    or c.path like concat(a.id,
                                    '.%')) 
                                where
                                    domain_id = 'CONDITION' 
                                    and is_standard = 0 
                                    and is_selectable = 1
                                )
                        )  
                        AND (
                            c_occurrence.PERSON_ID IN (
                                select
                                    person_id  
                                from
                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
                                where
                                    cb_search_person.person_id in (
                                        select
                                            criteria.person_id 
                                        from
                                            (select
                                                distinct person_id,
                                                entry_date,
                                                concept_id 
                                            from
                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                            where
                                                person_id in (
                                                    select
                                                        person_id 
                                                    from
                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                                    where
                                                        is_standard = 1 
                                                        and concept_id in (
                                                            select
                                                                distinct c.concept_id 
                                                            from
                                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                            join
                                                                (
                                                                    select
                                                                        cast(cr.id as string) as id 
                                                                    from
                                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                    where
                                                                        domain_id = 'CONDITION' 
                                                                        and is_standard = 1 
                                                                        and concept_id in (764949, 46274062, 4271333, 46270573, 4146581, 46273487, 46270028, 45768963, 42539549, 46269770, 4142738, 45768910, 443801, 4145356, 4152913, 45769350, 46273454, 4279553, 45769443, 317009, 314754, 4138760, 252946, 46269783, 46269790, 252658, 46269786, 45768965, 4051466, 46273462, 4245676, 252942, 4215802, 45772937, 40481763, 37108581, 4075237, 256448, 46269802, 4141978, 764677, 46270322, 4125022, 46269776, 45768964, 4233784, 4155468, 37310241, 46273635, 4207479, 4123253, 45769352, 4143828, 42535716, 257581, 46273452, 45771045, 46269778, 312950, 45769351, 4309833, 45768911, 36684328, 4308356, 313236, 46269789, 45768912, 761844, 42536208, 4145497, 4312524, 46270030, 46269787, 40483397, 45769438, 45769441, 43530693, 45773005, 4206340, 45766728, 4194289, 46270082, 45769442, 42538744, 4191479, 46269784, 4155469, 37116845) 
                                                                        and is_selectable = 1 
                                                                        and full_text like '%[condition_rank1]%'
                                                                ) a 
                                                                    on (
                                                                        c.path like concat('%.',
                                                                    a.id,
                                                                    '.%') 
                                                                    or c.path like concat('%.',
                                                                    a.id) 
                                                                    or c.path like concat(a.id,
                                                                    '.%')) 
                                                                where
                                                                    domain_id = 'CONDITION' 
                                                                    and is_standard = 1 
                                                                    and is_selectable = 1
                                                                )
                                                            union
                                                            all select
                                                                person_id 
                                                            from
                                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                                            where
                                                                is_standard = 0 
                                                                and concept_id in (
                                                                    select
                                                                        distinct c.concept_id 
                                                                    from
                                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                                    join
                                                                        (
                                                                            select
                                                                                cast(cr.id as string) as id 
                                                                            from
                                                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                            where
                                                                                domain_id = 'CONDITION' 
                                                                                and is_standard = 0 
                                                                                and concept_id in (46270322, 4155468, 46269789, 45572168, 45768965, 313236, 45768911, 4207479, 46273454, 44820889, 46270573, 44834769, 45601133, 45771045, 46269802, 4194289, 45567266, 44824288, 1569490, 45768912, 44829012, 4215802, 46269784, 44821988, 46270030, 42539549, 312950, 46269786, 764949, 4051466, 4245676, 45543269, 45543270, 45557626, 45769351, 4143828, 4152913, 45769442, 46273635, 45772937, 45548117, 4191479, 44832423, 4125022, 44833611, 45591559, 45576951, 4271333, 317009, 37310241, 4206340, 45548116, 45572170, 45562457, 4146581, 4123253, 256448, 46269776, 45768964, 46269787, 46273452, 44823144, 4312524, 4279553, 43530693, 42535716, 44830115, 46273487, 45769438, 4138760, 4155469, 36684328, 44831280, 1569491, 46269770, 40483397, 1569488, 44831278, 45576952, 45567265, 44824289, 44826679, 4141978, 45601134, 4145356, 43530700, 45773005, 4144757, 45581859, 45769441, 46269778, 4309833, 46269783, 4142738, 44831279, 4308356, 37116845, 44832424, 45581860, 257581, 44828510, 45768963, 764677, 44837136, 252658, 4145497, 46270028, 1569489, 46269790, 46273462, 45766728, 46270082, 44837135, 42536208, 42538744, 45768910, 37108581, 44821987, 35225323, 314754, 45586675, 40410639, 44824287, 761844, 45769352, 4075237, 45591558, 443801, 45572169, 45572171, 46274062, 4233784) 
                                                                                and is_selectable = 1 
                                                                                and full_text like '%[condition_rank1]%'
                                                                        ) a 
                                                                            on (
                                                                                c.path like concat('%.',
                                                                            a.id,
                                                                            '.%') 
                                                                            or c.path like concat('%.',
                                                                            a.id) 
                                                                            or c.path like concat(a.id,
                                                                            '.%')) 
                                                                        where
                                                                            domain_id = 'CONDITION' 
                                                                            and is_standard = 0 
                                                                            and is_selectable = 1
                                                                        )
                                                                )
                                                            ) criteria 
                                                    ) 
                                            )
                                        )
                                ) c_occurrence 
                            left join
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` c_type 
                                    on c_occurrence.CONDITION_TYPE_CONCEPT_ID = c_type.CONCEPT_ID 
                            left join
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` c_status 
                                    on c_occurrence.CONDITION_STATUS_CONCEPT_ID = c_status.CONCEPT_ID 
                            left join
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` c_standard_concept 
                                    on c_occurrence.CONDITION_CONCEPT_ID = c_standard_concept.CONCEPT_ID 
                            left join
                                `""" + os.environ["WORKSPACE_CDR"] + """.visit_occurrence` v 
                                    on c_occurrence.VISIT_OCCURRENCE_ID = v.VISIT_OCCURRENCE_ID 
                            left join
                                `""" + os.environ["WORKSPACE_CDR"] + """.concept` visit 
                                    on v.visit_concept_id = visit.concept_id"""

dataset_64469718_condition_df = pandas.read_gbq(dataset_64469718_condition_sql, dialect="standard", progress_bar_type="tqdm_notebook")

dataset_64469718_condition_df.head(5)

HBox(children=(FloatProgress(value=0.0, description='Downloading', max=590148.0, style=ProgressStyle(descriptiâ€¦

,CONDITION_START_DATETIME,CONDITION_END_DATETIME,STOP_REASON,PERSON_ID,CONDITION_TYPE_CONCEPT_NAME,CONDITION_STATUS_CONCEPT_NAME,STANDARD_CONCEPT_NAME,STANDARD_VOCABULARY,VISIT_OCCURRENCE_CONCEPT_NAME
0,2016-08-21 00:00:00+00:00,NaT,None,3347059,No matching concept,None,Uncomplicated asthma,SNOMED,None
1,2011-11-11 05:00:00+00:00,2011-11-11 05:00:00+00:00,None,1284243,EHR billing diagnosis,Final diagnosis,Asthma,SNOMED,None
2,2008-04-21 05:00:00+00:00,2008-04-21 00:00:00+00:00,None,2940808,Secondary Condition,Final diagnosis,Acute severe refractory exacerbation of asthma,SNOMED,None
3,2014-07-21 05:00:00+00:00,2014-07-21 05:00:00+00:00,None,1784187,Primary Condition,Final diagnosis,Acute exacerbation of asthma,SNOMED,None
4,2017-04-08 00:00:00+00:00,NaT,None,2032144,Patient Self-Reported Condition,No matching concept,Wheezing,SNOMED,None

In [33]:
condition_df=dataset_64469718_condition_df

In [34]:
condition_df= janitor.clean_names(condition_df)

In [13]:
# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = condition_df   

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'condition_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
os.system(f"gsutil cp './{destination_filename}' '{my_bucket}/data/'")
print(f'[INFO] {destination_filename} is successfully uploaded in your bucket.')

[INFO] condition_df.csv is successfully uploaded in your bucket.

In [14]:
condition_df.duplicated(subset='person_id').value_counts()

True     551043
False     39105
dtype: int64

In [38]:
import pandas
import os

# This query represents dataset "Asthma_exacerb_predict" for domain "drug" and was generated for All of Us Registered Tier Dataset v4
dataset_64469718_drug_sql = """
    SELECT
        d_exposure.PERSON_ID,
        d_exposure.DRUG_EXPOSURE_START_DATETIME,
        d_exposure.VERBATIM_END_DATE,
        d_exposure.REFILLS,
        d_exposure.DAYS_SUPPLY,
        d_exposure.QUANTITY,
        d_exposure.STOP_REASON,
        d_exposure.DRUG_EXPOSURE_END_DATETIME,
        d_route.concept_name as ROUTE_CONCEPT_NAME,
        d_type.concept_name as DRUG_TYPE_CONCEPT_NAME,
        d_standard_concept.concept_name as STANDARD_CONCEPT_NAME,
        d_standard_concept.vocabulary_id as STANDARD_VOCABULARY,
        d_source_concept.concept_name as SOURCE_CONCEPT_NAME,
        d_visit.concept_name as VISIT_OCCURRENCE_CONCEPT_NAME 
    from
        ( SELECT
            * 
        from
            `""" + os.environ["WORKSPACE_CDR"] + """.drug_exposure` d_exposure 
        WHERE
            (
                drug_concept_id in  (
                    select
                        distinct ca.descendant_id 
                    from
                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria_ancestor` ca 
                    join
                        (
                            select
                                distinct c.concept_id 
                            from
                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                            join
                                (
                                    select
                                        cast(cr.id as string) as id 
                                    from
                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                    where
                                        domain_id = 'DRUG' 
                                        and is_standard = 1 
                                        and concept_id in (
                                            1129625, 1140088, 1192218, 1326901, 1105775, 1181809, 1300153, 1134439, 43532539, 751698, 902938, 1196677, 1143374, 1154161, 1343916, 1183554, 711452, 1551099, 35603983, 1036525, 36883745, 1137529, 19029322, 905233, 43013634, 19126894, 1506270, 1111706, 19136048, 1237049, 1036059, 1110942, 35606631, 777221, 939259, 960900, 989878, 1163944, 1314928, 901656, 1115572, 1149380, 19050346, 19126511, 1112921, 19004810, 1101703, 914335, 919839, 19049024, 938205, 1154343, 19087208, 1147878, 734275, 792993, 19030493, 1780601, 915553, 1192710
                                        ) 
                                        and is_selectable = 1 
                                        and full_text like '%[drug_rank1]%'
                                ) a 
                                    on (
                                        c.path like concat('%.',
                                    a.id,
                                    '.%') 
                                    or c.path like concat('%.',
                                    a.id)) 
                                where
                                    domain_id = 'DRUG' 
                                    and is_standard = 1 
                                    and is_selectable = 1
                                ) b 
                                    on (
                                        ca.ancestor_id = b.concept_id
                                    )
                            )
                        )  
                        AND (
                            d_exposure.PERSON_ID IN (
                                select
                                    person_id  
                            from
                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
                            where
                                cb_search_person.person_id in (
                                    select
                                        criteria.person_id 
                                    from
                                        (select
                                            distinct person_id,
                                            entry_date,
                                            concept_id 
                                        from
                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                        where
                                            person_id in (
                                                select
                                                    person_id 
                                                from
                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                                where
                                                    is_standard = 1 
                                                    and concept_id in (
                                                        select
                                                            distinct c.concept_id 
                                                        from
                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                        join
                                                            (
                                                                select
                                                                    cast(cr.id as string) as id 
                                                                from
                                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                where
                                                                    domain_id = 'CONDITION' 
                                                                    and is_standard = 1 
                                                                    and concept_id in (764949, 46274062, 4271333, 46270573, 4146581, 46273487, 46270028, 45768963, 42539549, 46269770, 4142738, 45768910, 443801, 4145356, 4152913, 45769350, 46273454, 4279553, 45769443, 317009, 314754, 4138760, 252946, 46269783, 46269790, 252658, 46269786, 45768965, 4051466, 46273462, 4245676, 252942, 4215802, 45772937, 40481763, 37108581, 4075237, 256448, 46269802, 4141978, 764677, 46270322, 4125022, 46269776, 45768964, 4233784, 4155468, 37310241, 46273635, 4207479, 4123253, 45769352, 4143828, 42535716, 257581, 46273452, 45771045, 46269778, 312950, 45769351, 4309833, 45768911, 36684328, 4308356, 313236, 46269789, 45768912, 761844, 42536208, 4145497, 4312524, 46270030, 46269787, 40483397, 45769438, 45769441, 43530693, 45773005, 4206340, 45766728, 4194289, 46270082, 45769442, 42538744, 4191479, 46269784, 4155469, 37116845) 
                                                                    and is_selectable = 1 
                                                                    and full_text like '%[condition_rank1]%'
                                                            ) a 
                                                                on (
                                                                    c.path like concat('%.',
                                                                a.id,
                                                                '.%') 
                                                                or c.path like concat('%.',
                                                                a.id) 
                                                                or c.path like concat(a.id,
                                                                '.%')) 
                                                            where
                                                                domain_id = 'CONDITION' 
                                                                and is_standard = 1 
                                                                and is_selectable = 1
                                                            )
                                                        union
                                                        all select
                                                            person_id 
                                                        from
                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                                        where
                                                            is_standard = 0 
                                                            and concept_id in (
                                                                select
                                                                    distinct c.concept_id 
                                                                from
                                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                                join
                                                                    (
                                                                        select
                                                                            cast(cr.id as string) as id 
                                                                        from
                                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                        where
                                                                            domain_id = 'CONDITION' 
                                                                            and is_standard = 0 
                                                                            and concept_id in (46270322, 4155468, 46269789, 45572168, 45768965, 313236, 45768911, 4207479, 46273454, 44820889, 46270573, 44834769, 45601133, 45771045, 46269802, 4194289, 45567266, 44824288, 1569490, 45768912, 44829012, 4215802, 46269784, 44821988, 46270030, 42539549, 312950, 46269786, 764949, 4051466, 4245676, 45543269, 45543270, 45557626, 45769351, 4143828, 4152913, 45769442, 46273635, 45772937, 45548117, 4191479, 44832423, 4125022, 44833611, 45591559, 45576951, 4271333, 317009, 37310241, 4206340, 45548116, 45572170, 45562457, 4146581, 4123253, 256448, 46269776, 45768964, 46269787, 46273452, 44823144, 4312524, 4279553, 43530693, 42535716, 44830115, 46273487, 45769438, 4138760, 4155469, 36684328, 44831280, 1569491, 46269770, 40483397, 1569488, 44831278, 45576952, 45567265, 44824289, 44826679, 4141978, 45601134, 4145356, 43530700, 45773005, 4144757, 45581859, 45769441, 46269778, 4309833, 46269783, 4142738, 44831279, 4308356, 37116845, 44832424, 45581860, 257581, 44828510, 45768963, 764677, 44837136, 252658, 4145497, 46270028, 1569489, 46269790, 46273462, 45766728, 46270082, 44837135, 42536208, 42538744, 45768910, 37108581, 44821987, 35225323, 314754, 45586675, 40410639, 44824287, 761844, 45769352, 4075237, 45591558, 443801, 45572169, 45572171, 46274062, 4233784) 
                                                                            and is_selectable = 1 
                                                                            and full_text like '%[condition_rank1]%'
                                                                    ) a 
                                                                        on (
                                                                            c.path like concat('%.',
                                                                        a.id,
                                                                        '.%') 
                                                                        or c.path like concat('%.',
                                                                        a.id) 
                                                                        or c.path like concat(a.id,
                                                                        '.%')) 
                                                                    where
                                                                        domain_id = 'CONDITION' 
                                                                        and is_standard = 0 
                                                                        and is_selectable = 1
                                                                    )
                                                            )
                                                        ) criteria 
                                                ) 
                                        )
                                    )
                            ) d_exposure 
                        LEFT JOIN
                            `""" + os.environ["WORKSPACE_CDR"] + """.concept` d_route 
                                on d_exposure.ROUTE_CONCEPT_ID = d_route.CONCEPT_ID 
                        LEFT JOIN
                            `""" + os.environ["WORKSPACE_CDR"] + """.concept` d_type 
                                on d_exposure.drug_type_concept_id = d_type.CONCEPT_ID 
                        left join
                            `""" + os.environ["WORKSPACE_CDR"] + """.concept` d_standard_concept 
                                on d_exposure.DRUG_CONCEPT_ID = d_standard_concept.CONCEPT_ID 
                        LEFT JOIN
                            `""" + os.environ["WORKSPACE_CDR"] + """.concept` d_source_concept 
                                on d_exposure.DRUG_SOURCE_CONCEPT_ID = d_source_concept.CONCEPT_ID 
                        left join
                            `""" + os.environ["WORKSPACE_CDR"] + """.visit_occurrence` v 
                                on d_exposure.VISIT_OCCURRENCE_ID = v.VISIT_OCCURRENCE_ID 
                        LEFT JOIN
                            `""" + os.environ["WORKSPACE_CDR"] + """.concept` d_visit 
                                on v.VISIT_CONCEPT_ID = d_visit.CONCEPT_ID"""

dataset_64469718_drug_df = pandas.read_gbq(dataset_64469718_drug_sql, dialect="standard", progress_bar_type="tqdm_notebook")

dataset_64469718_drug_df.head(5)

HBox(children=(FloatProgress(value=0.0, description='Downloading', max=2281280.0, style=ProgressStyle(descriptâ€¦

,PERSON_ID,DRUG_EXPOSURE_START_DATETIME,VERBATIM_END_DATE,REFILLS,DAYS_SUPPLY,QUANTITY,STOP_REASON,DRUG_EXPOSURE_END_DATETIME,ROUTE_CONCEPT_NAME,DRUG_TYPE_CONCEPT_NAME,STANDARD_CONCEPT_NAME,STANDARD_VOCABULARY,SOURCE_CONCEPT_NAME,VISIT_OCCURRENCE_CONCEPT_NAME
0,2620809,2016-07-09 05:00:00+00:00,NaT,NaN,0.0,0.0,None,NaT,No matching concept,Prescription dispensed in pharmacy,phenobarbital 130 MG/ML Injectable Solution,RxNorm,phenobarbital 130 MG/ML Injectable Solution,None
1,2443991,2016-05-21 05:00:00+00:00,NaT,NaN,0.0,0.0,None,NaT,No matching concept,Prescription dispensed in pharmacy,10 ML atropine sulfate 0.1 MG/ML Prefilled Syr...,RxNorm,10 ML atropine sulfate 0.1 MG/ML Prefilled Syr...,None
2,3258214,2016-10-22 05:00:00+00:00,NaT,NaN,30.0,30.0,None,NaT,Oral,Prescription dispensed in pharmacy,montelukast 10 MG Oral Tablet,RxNorm,montelukast 10 MG Oral Tablet,None
3,2078640,2018-07-02 07:17:31+00:00,NaT,NaN,30.0,1.0,None,2018-08-01 07:17:31+00:00,Inhalation,Prescription dispensed in pharmacy,120 ACTUAT budesonide 0.08 MG/ACTUAT / formote...,RxNorm,120 ACTUAT budesonide 0.08 MG/ACTUAT / formote...,None
4,2807206,2014-08-22 05:00:00+00:00,NaT,NaN,6.0,21.0,None,NaT,Oral,Prescription dispensed in pharmacy,{21 (methylprednisolone 4 MG Oral Tablet) } Pack,RxNorm,{21 (methylprednisolone 4 MG Oral Tablet) } Pack,None

In [39]:
drug_df=dataset_64469718_drug_df

In [40]:
drug_df=janitor.clean_names(drug_df)

In [18]:
# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = drug_df   

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'drug_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
os.system(f"gsutil cp './{destination_filename}' '{my_bucket}/data/'")
print(f'[INFO] {destination_filename} is successfully uploaded in your bucket.')

[INFO] drug_df.csv is successfully uploaded in your bucket.

In [19]:
drug_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2281280 entries, 0 to 2281279
Data columns (total 14 columns):
 #   Column                         Dtype
---  ------                         -----
 0   person_id                      int64
 1   drug_exposure_start_datetime   datetime64[ns, UTC]
 2   verbatim_end_date              datetime64[ns]
 3   refills                        float64
 4   days_supply                    float64
 5   quantity                       float64
 6   stop_reason                    object
 7   drug_exposure_end_datetime     datetime64[ns, UTC]
 8   route_concept_name             object
 9   drug_type_concept_name         object
 10  standard_concept_name          object
 11  standard_vocabulary            object
 12  source_concept_name            object
 13  visit_occurrence_concept_name  object
dtypes: datetime64[ns, UTC](2), datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 243.7+ MB

In [ ]:
drug_df.sort_values('person_id').head(60)

In [3]:
import pandas
import os

# This query represents dataset "Asthma_exacerb_predict" for domain "measurement" and was generated for All of Us Registered Tier Dataset v4
dataset_64469718_measurement_sql = """
    SELECT
        measurement.RANGE_HIGH,
        measurement.RANGE_LOW,
        measurement.MEASUREMENT_DATETIME,
        measurement.PERSON_ID,
        measurement.VALUE_AS_NUMBER,
        m_value.concept_name as VALUE_AS_CONCEPT_NAME,
        m_type.concept_name as MEASUREMENT_TYPE_CONCEPT_NAME,
        m_standard_concept.concept_name as STANDARD_CONCEPT_NAME,
        m_standard_concept.vocabulary_id as STANDARD_VOCABULARY,
        m_visit.concept_name as VISIT_OCCURRENCE_CONCEPT_NAME 
    from
        ( SELECT
            * 
        from
            `""" + os.environ["WORKSPACE_CDR"] + """.measurement` measurement 
        WHERE
            (
                measurement_concept_id in  (
                    select
                        distinct c.concept_id 
                    from
                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                    join
                        (
                            select
                                cast(cr.id as string) as id 
                            from
                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                            where
                                domain_id = 'MEASUREMENT' 
                                and is_standard = 1 
                                and concept_id in (
                                    3034806, 3012030, 3020825, 3024128, 3018645, 3022675, 3035995, 3021304, 3013682, 3020874, 3033575, 3005333, 3023599, 3024929, 3021601, 3045716, 3009537, 3037235, 3027796, 3000131, 3023006, 3036277, 3002187, 3003888, 3013650, 3015731, 3005235, 3025260, 3011948, 3027300, 3036780, 3001915, 3014599, 3027597, 3007490, 3004327, 3024180, 3005136, 3024469, 3016723, 3001965, 3009744, 3009745, 3037475, 3010702, 3015632, 3012494, 3024171, 3004501, 3001247, 3002527, 3012932, 3020934, 3036312, 3023314, 3022100, 3024561, 3013429, 3036857, 3020630, 3000876, 3015411, 3009201, 3028615, 3006451, 3024395, 3008342, 3035362, 3016459, 3011397, 3026212, 3007070, 3000348, 3008450, 3016031, 3020416, 3010457, 37023425, 3028352, 3002479, 3024149, 3008401, 3011951, 3006906, 3012711, 3026915, 3023430, 3043730, 3019897, 3023646, 3001539, 3019550, 3007980, 3014133, 3006923, 3013043, 3007757, 3038205, 3024009, 3027114, 3022217, 3021226, 3022192, 3037511, 3006594, 3013721, 3027231, 3007015, 3022260, 3038553, 3006734, 3028668, 3036067, 3013101, 3013869, 3043111, 3011177, 3015942, 3025315, 3011360, 3033335, 3000963, 3027794, 40783188, 3018834, 3000905, 3023351, 3014126, 3015142, 40796119, 3015076, 3016835
                                ) 
                                and is_selectable = 1 
                                and full_text like '%[measurement_rank1]%'
                        ) a 
                            on (
                                c.path like concat('%.',
                            a.id,
                            '.%') 
                            or c.path like concat('%.',
                            a.id) 
                            or c.path like concat(a.id,
                            '.%')) 
                        where
                            domain_id = 'MEASUREMENT' 
                            and is_standard = 1 
                            and is_selectable = 1
                        )
                )  
                AND (
                    measurement.PERSON_ID IN (
                        select
                            person_id  
                        from
                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
                        where
                            cb_search_person.person_id in (
                                select
                                    criteria.person_id 
                                from
                                    (select
                                        distinct person_id,
                                        entry_date,
                                        concept_id 
                                    from
                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                    where
                                        person_id in (
                                            select
                                                person_id 
                                            from
                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                            where
                                                is_standard = 1 
                                                and concept_id in (
                                                    select
                                                        distinct c.concept_id 
                                                    from
                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                    join
                                                        (
                                                            select
                                                                cast(cr.id as string) as id 
                                                            from
                                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                            where
                                                                domain_id = 'CONDITION' 
                                                                and is_standard = 1 
                                                                and concept_id in (764949, 46274062, 4271333, 46270573, 4146581, 46273487, 46270028, 45768963, 42539549, 46269770, 4142738, 45768910, 443801, 4145356, 4152913, 45769350, 46273454, 4279553, 45769443, 317009, 314754, 4138760, 252946, 46269783, 46269790, 252658, 46269786, 45768965, 4051466, 46273462, 4245676, 252942, 4215802, 45772937, 40481763, 37108581, 4075237, 256448, 46269802, 4141978, 764677, 46270322, 4125022, 46269776, 45768964, 4233784, 4155468, 37310241, 46273635, 4207479, 4123253, 45769352, 4143828, 42535716, 257581, 46273452, 45771045, 46269778, 312950, 45769351, 4309833, 45768911, 36684328, 4308356, 313236, 46269789, 45768912, 761844, 42536208, 4145497, 4312524, 46270030, 46269787, 40483397, 45769438, 45769441, 43530693, 45773005, 4206340, 45766728, 4194289, 46270082, 45769442, 42538744, 4191479, 46269784, 4155469, 37116845) 
                                                                and is_selectable = 1 
                                                                and full_text like '%[condition_rank1]%'
                                                        ) a 
                                                            on (
                                                                c.path like concat('%.',
                                                            a.id,
                                                            '.%') 
                                                            or c.path like concat('%.',
                                                            a.id) 
                                                            or c.path like concat(a.id,
                                                            '.%')) 
                                                        where
                                                            domain_id = 'CONDITION' 
                                                            and is_standard = 1 
                                                            and is_selectable = 1
                                                        )
                                                    union
                                                    all select
                                                        person_id 
                                                    from
                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                                    where
                                                        is_standard = 0 
                                                        and concept_id in (
                                                            select
                                                                distinct c.concept_id 
                                                            from
                                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                            join
                                                                (
                                                                    select
                                                                        cast(cr.id as string) as id 
                                                                    from
                                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                    where
                                                                        domain_id = 'CONDITION' 
                                                                        and is_standard = 0 
                                                                        and concept_id in (46270322, 4155468, 46269789, 45572168, 45768965, 313236, 45768911, 4207479, 46273454, 44820889, 46270573, 44834769, 45601133, 45771045, 46269802, 4194289, 45567266, 44824288, 1569490, 45768912, 44829012, 4215802, 46269784, 44821988, 46270030, 42539549, 312950, 46269786, 764949, 4051466, 4245676, 45543269, 45543270, 45557626, 45769351, 4143828, 4152913, 45769442, 46273635, 45772937, 45548117, 4191479, 44832423, 4125022, 44833611, 45591559, 45576951, 4271333, 317009, 37310241, 4206340, 45548116, 45572170, 45562457, 4146581, 4123253, 256448, 46269776, 45768964, 46269787, 46273452, 44823144, 4312524, 4279553, 43530693, 42535716, 44830115, 46273487, 45769438, 4138760, 4155469, 36684328, 44831280, 1569491, 46269770, 40483397, 1569488, 44831278, 45576952, 45567265, 44824289, 44826679, 4141978, 45601134, 4145356, 43530700, 45773005, 4144757, 45581859, 45769441, 46269778, 4309833, 46269783, 4142738, 44831279, 4308356, 37116845, 44832424, 45581860, 257581, 44828510, 45768963, 764677, 44837136, 252658, 4145497, 46270028, 1569489, 46269790, 46273462, 45766728, 46270082, 44837135, 42536208, 42538744, 45768910, 37108581, 44821987, 35225323, 314754, 45586675, 40410639, 44824287, 761844, 45769352, 4075237, 45591558, 443801, 45572169, 45572171, 46274062, 4233784) 
                                                                        and is_selectable = 1 
                                                                        and full_text like '%[condition_rank1]%'
                                                                ) a 
                                                                    on (
                                                                        c.path like concat('%.',
                                                                    a.id,
                                                                    '.%') 
                                                                    or c.path like concat('%.',
                                                                    a.id) 
                                                                    or c.path like concat(a.id,
                                                                    '.%')) 
                                                                where
                                                                    domain_id = 'CONDITION' 
                                                                    and is_standard = 0 
                                                                    and is_selectable = 1
                                                                )
                                                        )
                                                    ) criteria 
                                            ) 
                                    )
                                )
                        ) measurement 
                    left join
                        `""" + os.environ["WORKSPACE_CDR"] + """.concept` m_value 
                            on measurement.value_as_concept_id = m_value.concept_id 
                    left join
                        `""" + os.environ["WORKSPACE_CDR"] + """.concept` m_type 
                            on measurement.measurement_type_concept_id = m_type.concept_id 
                    left join
                        `""" + os.environ["WORKSPACE_CDR"] + """.concept` m_standard_concept 
                            on measurement.measurement_concept_id = m_standard_concept.concept_id 
                    left join
                        `""" + os.environ["WORKSPACE_CDR"] + """.visit_occurrence` v 
                            on measurement.visit_occurrence_id = v.visit_occurrence_id 
                    left join
                        `""" + os.environ["WORKSPACE_CDR"] + """.concept` m_visit 
                            on v.visit_concept_id = m_visit.concept_id"""

dataset_64469718_measurement_df = pandas.read_gbq(dataset_64469718_measurement_sql, dialect="standard", progress_bar_type="tqdm_notebook")

dataset_64469718_measurement_df.head(5)

HBox(children=(FloatProgress(value=0.0, description='Downloading', max=41504278.0, style=ProgressStyle(descripâ€¦

,RANGE_HIGH,RANGE_LOW,MEASUREMENT_DATETIME,PERSON_ID,VALUE_AS_NUMBER,VALUE_AS_CONCEPT_NAME,MEASUREMENT_TYPE_CONCEPT_NAME,STANDARD_CONCEPT_NAME,STANDARD_VOCABULARY,VISIT_OCCURRENCE_CONCEPT_NAME
0,1.035,1.001,2017-07-24 05:01:00+00:00,2627490,1.019,No matching concept,Lab result,Specific gravity of Urine by Test strip,LOINC,None
1,1.900,0.830,2016-12-28 07:35:00+00:00,1144394,0.850,None,Lab result,Thyroxine (T4) free [Mass/volume] in Serum or ...,LOINC,None
2,NaN,NaN,2019-07-19 01:07:00+00:00,3413544,0.200,None,Lab result,Urobilinogen [Mass/volume] in Urine by Test strip,LOINC,None
3,305.000,278.000,2016-09-14 19:07:00+00:00,1035182,295.000,No matching concept,Lab result,Osmolality of Serum or Plasma,LOINC,None
4,NaN,NaN,2018-01-26 13:21:00+00:00,1940125,NaN,Negative,Lab result,Glucose [Mass/volume] in Urine,LOINC,None

In [12]:
measurement_df=dataset_64469718_measurement_df

In [13]:
measurement_df=janitor.clean_names(measurement_df)

In [14]:
# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = measurement_df   

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'measurement_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
os.system(f"gsutil cp './{destination_filename}' '{my_bucket}/data/'")
print(f'[INFO] {destination_filename} is successfully uploaded in your bucket.')

[INFO] measurement_df.csv is successfully uploaded in your bucket.

In [15]:
measurement_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41504278 entries, 0 to 41504277
Data columns (total 10 columns):
 #   Column                         Dtype
---  ------                         -----
 0   range_high                     float64
 1   range_low                      float64
 2   measurement_datetime           datetime64[ns, UTC]
 3   person_id                      int64
 4   value_as_number                float64
 5   value_as_concept_name          object
 6   measurement_type_concept_name  object
 7   standard_concept_name          object
 8   standard_vocabulary            object
 9   visit_occurrence_concept_name  object
dtypes: datetime64[ns, UTC](1), float64(3), int64(1), object(5)
memory usage: 3.1+ GB

In [16]:
measurement_df.sort_values('person_id').head(60)

,range_high,range_low,measurement_datetime,person_id,value_as_number,value_as_concept_name,measurement_type_concept_name,standard_concept_name,standard_vocabulary,visit_occurrence_concept_name
36181052,450.0,150.0,2019-03-30 06:00:01+00:00,1000042,295.000000,No matching concept,Lab observation numeric result,Platelets [#/volume] in Blood by Automated count,LOINC,None
6588986,4.5,2.5,2000-06-01 10:00:00+00:00,1000042,4.400000,No matching concept,Lab observation numeric result,Phosphate [Mass/volume] in Serum or Plasma,LOINC,None
6001968,95.0,80.0,2019-03-30 06:00:01+00:00,1000042,74.500000,No matching concept,Lab observation numeric result,MCV [Entitic volume] by Automated count,LOINC,None
6520519,110.0,100.0,2019-05-12 11:04:49+00:00,1000042,104.000000,No matching concept,Lab observation numeric result,Chloride [Moles/volume] in Serum or Plasma,LOINC,None
20730404,NaN,60.0,2013-06-26 04:01:33+00:00,1000042,92.000000,No matching concept,Lab observation numeric result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,None
24757153,121.0,42.0,2017-08-17 16:07:02+00:00,1000042,72.000000,No matching concept,Lab observation numeric result,Alkaline phosphatase [Enzymatic activity/volum...,LOINC,None
15376611,NaN,0.8,2016-09-08 10:37:32+00:00,1000042,2.800000,No matching concept,Lab observation numeric result,INR in Platelet poor plasma by Coagulation assay,LOINC,None
915877,NaN,NaN,2013-10-28 10:16:39+00:00,1000042,187.960000,No matching concept,From physical examination,Body height,LOINC,None
22893728,8.5,6.0,2000-06-01 10:00:00+00:00,1000042,7.400000,No matching concept,Lab observation numeric result,Protein [Mass/volume] in Serum or Plasma,LOINC,None
37342786,NaN,59.0,2011-05-05 14:45:02+00:00,1000042,98.000000,No matching concept,Lab observation numeric result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,None
30419237,NaN,NaN,2019-03-23 16:12:49+00:00,1000042,6.500000,No matching concept,Lab observation numeric result,Anion gap in Serum or Plasma,LOINC,None
7645197,12.0,2.0,2019-03-30 06:00:01+00:00,1000042,13.200000,No matching concept,Lab observation numeric result,Monocytes/100 leukocytes in Blood by Automated...,LOINC,None
19652717,0.2,0.0,2017-08-29 06:00:00+00:00,1000042,0.100000,No matching concept,Lab observation numeric result,Bilirubin.direct [Mass/volume] in Serum or Plasma,LOINC,None
37036573,14.5,11.5,2011-08-07 08:44:32+00:00,1000042,16.100000,No matching concept,Lab observation numeric result,Erythrocyte distribution width [Ratio] by Auto...,LOINC,None
1281029,NaN,NaN,2016-10-31 09:43:41+00:00,1000042,18.000000,No matching concept,From physical examination,Respiratory rate,LOINC,None
38000715,0.2,0.0,2017-03-28 07:41:46+00:00,1000042,0.200000,No matching concept,Lab observation numeric result,Bilirubin.direct [Mass/volume] in Serum or Plasma,LOINC,None
28789779,14.5,11.5,2015-05-18 09:23:59+00:00,1000042,16.900000,No matching concept,Lab observation numeric result,Erythrocyte distribution width [Ratio] by Auto...,LOINC,None
28394186,12.0,2.0,2018-02-20 15:27:06+00:00,1000042,15.500000,No matching concept,Lab observation numeric result,Monocytes/100 leukocytes in Blood by Automated...,LOINC,None
470075,NaN,NaN,2017-08-17 16:07:04+00:00,1000042,0.000000,No matching concept,Lab observation numeric result,Hemoglobin [Presence] in Urine,LOINC,None
30436929,NaN,NaN,2011-08-07 08:44:31+00:00,1000042,8.000000,No matching concept,Lab observation numeric result,Anion gap in Serum or Plasma,LOINC,None
17888042,NaN,NaN,2013-08-12 20:51:52+00:00,1000042,18.000000,No matching concept,From physical examination,Respiratory rate,LOINC,None
6001979,95.0,80.0,2017-11-28 08:39:05+00:00,1000042,77.700000,No matching concept,Lab observation numeric result,MCV [Entitic volume] by Automated count,LOINC,None
4142147,NaN,60.0,2017-08-17 08:19:02+00:00,1000042,101.000000,No matching concept,Lab observation numeric result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,None
10301324,10.2,8.4,2017-01-23 09:28:05+00:00,1000042,9.100000,No matching concept,Lab observation numeric result,Calcium [Mass/volume] in Serum or Plasma,LOINC,None
31073797,120.0,75.0,2011-05-05 14:45:02+00:00,1000042,92.000000,No matching concept,Lab observation numeric result,Glucose [Mass/volume] in Serum or Plasma,LOINC,None
23589259,0.2,0.0,2017-11-29 06:00:01+00:00,1000042,0.010000,No matching concept,Lab observation numeric result,Basophils [#/volume] in Blood by Automated count,LOINC,None
28851032,121.0,42.0,2012-05-07 12:55:26+00:00,1000042,76.000000,No matching concept,Lab observation numeric result,Alkaline phosphatase [Enzymatic activity/volum...,LOINC,None
34474302,NaN,NaN,2013-12-31 16:45:00+00:00,1000042,18.000000,No matching concept,From physical examination,Respiratory rate,LOINC,None
7809600,32.0,24.0,2014-01-01 06:00:00+00:00,1000042,32.000000,No matching concept,Lab observation numeric result,"Carbon dioxide, total [Moles/volume] in Serum ...",LOINC,None
18272272,36.0,32.0,2018-04-29 10:28:23+00:00,1000042,31.900000,No matching concept,Lab observation numeric result,MCHC [Mass/volume] by Automated count,LOINC,None
35113523,5.1,3.8,2011-08-07 08:44:31+00:00,1000042,4.100000,No matching concept,Lab observation numeric result,Albumin [Mass/volume] in Serum or Plasma,LOINC,None
37146103,10.5,7.5,2019-09-26 12:19:49+00:00,1000042,9.500000,No matching concept,Lab observation numeric result,Platelet mean volume [Entitic volume] in Blood...,LOINC,None
15649353,0.7,0.0,2017-08-30 06:00:01+00:00,1000042,0.120000,No matching concept,Lab observation numeric result,Eosinophils [#/volume] in Blood by Automated c...,LOINC,None
19240088,5.0,3.5,2013-10-28 09:26:11+00:00,1000042,3.800000,No matching concept,Lab observation numeric result,Potassium [Moles/volume] in Serum or Plasma,LOINC,None
22327364,180.0,140.0,2006-03-05 16:20:01+00:00,1000042,125.000000,No matching concept,Lab observation numeric result,Hemoglobin [Mass/volume] in Blood,LOINC,None
943723,NaN,NaN,2008-02-26 07:52:04+00:00,1000042,185.420000,No matching concept,From physical examination,Body height,LOINC,None
17892439,NaN,NaN,2001-05-21 12:55:00+00:00,1000042,18.000000,No matching concept,From physical examination,Respiratory rate,LOINC,None
943726,NaN,NaN,2018-04-29 12:56:37+00:00,1000042,187.960000,No matching concept,From physical examination,Body height,LOINC,None
37000894,52.0,40.0,2013-02-27 12:24:21+00:00,1000042,40.300000,No matching concept,Lab observation numeric result,Hematocrit [Volume Fraction] of Blood by Autom...,LOINC,None
11776019,12.0,2.0,2019-04-07 13:04:18+00:00,1000042,9.300000,No matching concept,Lab observation numeric result,Monocytes/100 leukocytes in Blood by Automated...,LOINC,None
9903802,33.0,27.0,2012-05-13 10:00:51+00:00,1000042,26.800000,No matching concept,Lab observation numeric result,MCH [Entitic mass] by Automated count,LOINC,None
12394331,42.0,10.0,2018-02-20 15:27:05+00:00,1000042,33.000000,No matching concept,Lab observation numeric result,Aspartate aminotransferase [Enzymatic activity...,LOINC,None
4157263,125.0,25.0,2012-05-13 10:00:52+00:00,1000042,50.000000,No matching concept,Lab observation numeric result,Amylase [Enzymatic activity/volume] in Serum o...,LOINC,None
20751131,NaN,60.0,2019-03-30 06:00:00+00:00,1000042,101.000000,No matching concept,Lab observation numeric result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,None
13639354,NaN,NaN,2006-07-18 09:35:05+00:00,1000042,16.000000,No matching concept,From physical examination,Respiratory rate,LOINC,None
30982718,10.2,8.4,2019-03-21 01:25:32+00:00,1000042,7.900000,No matching concept,Lab observation numeric result,Calcium [Mass/volume] in Serum or Plasma,LOINC,None
37327852,NaN,60.0,2019-02-21 10:46:55+00:00,1000042,114.000000,No matching concept,Lab observation numeric result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,None
19471754,1.2,0.1,2019-09-26 12:19:47+00:00,1000042,0.500000,No matching concept,Lab observation numeric result,Bilirubin.total [Mass/volume] in Serum or Plasma,LOINC,None
30032787,NaN,NaN,2018-05-10 14:10:18+00:00,1000042,149.687018,No matching concept,From physical examination,Body weight,LOINC,None
12982258,NaN,NaN,2009-04-05 11:00:05+00:00,1000042,0.000000,No matching concept,Lab observation numeric result,Bilirubin.direct [Mass/volume] in Serum or Plasma,LOINC,None
15142120,240.0,114.0,2008-02-26 08:40:01+00:00,1000042,134.000000,No matching concept,Lab observation numeric result,Cholesterol [Mass/volume] in Serum or Plasma,LOINC,None
33990035,145.0,135.0,2017-08-19 19:14:34+00:00,1000042,133.000000,No matching concept,Lab observation numeric result,Sodium [Moles/volume] in Blood,LOINC,None
12254458,121.0,42.0,2019-10-14 09:42:25+00:00,1000042,63.000000,No matching concept,Lab observation numeric result,Alkaline phosphatase [Enzymatic activity/volum...,LOINC,None
36259076,NaN,NaN,2013-08-02 21:14:23+00:00,1000042,0.000000,No matching concept,Lab observation numeric result,Bilirubin.total [Presence] in Urine by Test strip,LOINC,None
26775929,51.0,38.0,2017-08-19 06:00:00+00:00,1000042,37.000000,No matching concept,Lab observation numeric result,Albumin [Mass/volume] in Serum or Plasma,LOINC,None
24359691,3.5,1.2,2016-11-24 10:30:39+00:00,1000042,1.560000,No matching concept,Lab observation numeric result,Lymphocytes/100 leukocytes in Blood by Automat...,LOINC,None
10115938,95.0,80.0,2018-05-15 13:55:19+00:00,1000042,73.300000,No matching concept,Lab observation numeric result,MCV [Entitic volume] by Automated count,LOINC,None
28841794,10.5,7.5,2017-10-04 08:28:53+00:00,1000042,9.800000,No matching concept,Lab observation numeric result,Platelet mean volume [Entitic volume] in Blood...,LOINC,None
5020035,NaN,NaN,2000-11-23 11:31:00+00:00,1000042,187.960000,No matching concept,From physical examination,Body height,LOINC,None
2920280,NaN,0.8,2012-06-04 09:15:55+00:00,1000042,2.000000,No matching concept,Lab observation numeric result,INR in Platelet poor plasma by Coagulation assay,LOINC,None

In [17]:
import pandas
import os

# This query represents dataset "Asthma_exacerb_predict" for domain "observation" and was generated for All of Us Registered Tier Dataset v4
dataset_64469718_observation_sql = """
    SELECT
        observation.VALUE_AS_STRING,
        observation.OBSERVATION_DATETIME,
        observation.PERSON_ID,
        observation.VALUE_AS_NUMBER,
        o_unit.concept_name as UNIT_CONCEPT_NAME,
        o_value.concept_name as VALUE_AS_CONCEPT_NAME,
        o_type.concept_name as OBSERVATION_TYPE_CONCEPT_NAME,
        o_qualifier.concept_name as QUALIFIER_CONCEPT_NAME,
        o_standard_concept.concept_name as STANDARD_CONCEPT_NAME,
        o_standard_concept.vocabulary_id as STANDARD_VOCABULARY,
        o_visit.concept_name as VISIT_OCCURRENCE_CONCEPT_NAME 
    from
        ( SELECT
            * 
        from
            `""" + os.environ["WORKSPACE_CDR"] + """.ds_observation` observation 
        WHERE
            (
                observation_concept_id in (
                    1585636, 40766240, 1586182, 3035281, 1586213, 3022304, 40764347, 40771091, 3046344, 3046853, 40771090, 40766609, 1585389, 1586166, 4087925, 3007191, 1586140, 3046965, 1585370, 1585886, 1586174, 40766306, 46235933, 43530559
                )
            )  
            AND (
                observation.PERSON_ID IN (
                    select
                        person_id  
                    from
                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
                    where
                        cb_search_person.person_id in (
                            select
                                criteria.person_id 
                            from
                                (select
                                    distinct person_id,
                                    entry_date,
                                    concept_id 
                                from
                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                where
                                    person_id in (
                                        select
                                            person_id 
                                        from
                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                        where
                                            is_standard = 1 
                                            and concept_id in (
                                                select
                                                    distinct c.concept_id 
                                                from
                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                join
                                                    (
                                                        select
                                                            cast(cr.id as string) as id 
                                                        from
                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                        where
                                                            domain_id = 'CONDITION' 
                                                            and is_standard = 1 
                                                            and concept_id in (764949, 46274062, 4271333, 46270573, 4146581, 46273487, 46270028, 45768963, 42539549, 46269770, 4142738, 45768910, 443801, 4145356, 4152913, 45769350, 46273454, 4279553, 45769443, 317009, 314754, 4138760, 252946, 46269783, 46269790, 252658, 46269786, 45768965, 4051466, 46273462, 4245676, 252942, 4215802, 45772937, 40481763, 37108581, 4075237, 256448, 46269802, 4141978, 764677, 46270322, 4125022, 46269776, 45768964, 4233784, 4155468, 37310241, 46273635, 4207479, 4123253, 45769352, 4143828, 42535716, 257581, 46273452, 45771045, 46269778, 312950, 45769351, 4309833, 45768911, 36684328, 4308356, 313236, 46269789, 45768912, 761844, 42536208, 4145497, 4312524, 46270030, 46269787, 40483397, 45769438, 45769441, 43530693, 45773005, 4206340, 45766728, 4194289, 46270082, 45769442, 42538744, 4191479, 46269784, 4155469, 37116845) 
                                                            and is_selectable = 1 
                                                            and full_text like '%[condition_rank1]%'
                                                    ) a 
                                                        on (
                                                            c.path like concat('%.',
                                                        a.id,
                                                        '.%') 
                                                        or c.path like concat('%.',
                                                        a.id) 
                                                        or c.path like concat(a.id,
                                                        '.%')) 
                                                    where
                                                        domain_id = 'CONDITION' 
                                                        and is_standard = 1 
                                                        and is_selectable = 1
                                                    )
                                                union
                                                all select
                                                    person_id 
                                                from
                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                                where
                                                    is_standard = 0 
                                                    and concept_id in (
                                                        select
                                                            distinct c.concept_id 
                                                        from
                                                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                        join
                                                            (
                                                                select
                                                                    cast(cr.id as string) as id 
                                                                from
                                                                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                                where
                                                                    domain_id = 'CONDITION' 
                                                                    and is_standard = 0 
                                                                    and concept_id in (46270322, 4155468, 46269789, 45572168, 45768965, 313236, 45768911, 4207479, 46273454, 44820889, 46270573, 44834769, 45601133, 45771045, 46269802, 4194289, 45567266, 44824288, 1569490, 45768912, 44829012, 4215802, 46269784, 44821988, 46270030, 42539549, 312950, 46269786, 764949, 4051466, 4245676, 45543269, 45543270, 45557626, 45769351, 4143828, 4152913, 45769442, 46273635, 45772937, 45548117, 4191479, 44832423, 4125022, 44833611, 45591559, 45576951, 4271333, 317009, 37310241, 4206340, 45548116, 45572170, 45562457, 4146581, 4123253, 256448, 46269776, 45768964, 46269787, 46273452, 44823144, 4312524, 4279553, 43530693, 42535716, 44830115, 46273487, 45769438, 4138760, 4155469, 36684328, 44831280, 1569491, 46269770, 40483397, 1569488, 44831278, 45576952, 45567265, 44824289, 44826679, 4141978, 45601134, 4145356, 43530700, 45773005, 4144757, 45581859, 45769441, 46269778, 4309833, 46269783, 4142738, 44831279, 4308356, 37116845, 44832424, 45581860, 257581, 44828510, 45768963, 764677, 44837136, 252658, 4145497, 46270028, 1569489, 46269790, 46273462, 45766728, 46270082, 44837135, 42536208, 42538744, 45768910, 37108581, 44821987, 35225323, 314754, 45586675, 40410639, 44824287, 761844, 45769352, 4075237, 45591558, 443801, 45572169, 45572171, 46274062, 4233784) 
                                                                    and is_selectable = 1 
                                                                    and full_text like '%[condition_rank1]%'
                                                            ) a 
                                                                on (
                                                                    c.path like concat('%.',
                                                                a.id,
                                                                '.%') 
                                                                or c.path like concat('%.',
                                                                a.id) 
                                                                or c.path like concat(a.id,
                                                                '.%')) 
                                                            where
                                                                domain_id = 'CONDITION' 
                                                                and is_standard = 0 
                                                                and is_selectable = 1
                                                            )
                                                    )
                                                ) criteria 
                                        ) 
                                )
                            )
                    ) observation 
                LEFT JOIN
                    `""" + os.environ["WORKSPACE_CDR"] + """.concept` o_unit 
                        on observation.unit_concept_id = o_unit.CONCEPT_ID 
                LEFT JOIN
                    `""" + os.environ["WORKSPACE_CDR"] + """.concept` o_value 
                        on observation.value_as_concept_id = o_value.CONCEPT_ID 
                LEFT JOIN
                    `""" + os.environ["WORKSPACE_CDR"] + """.concept` o_type 
                        on observation.OBSERVATION_TYPE_CONCEPT_ID = o_type.CONCEPT_ID 
                LEFT JOIN
                    `""" + os.environ["WORKSPACE_CDR"] + """.concept` o_qualifier 
                        on observation.qualifier_concept_id = o_qualifier.CONCEPT_ID 
                LEFT JOIN
                    `""" + os.environ["WORKSPACE_CDR"] + """.concept` o_standard_concept 
                        on observation.OBSERVATION_CONCEPT_ID = o_standard_concept.CONCEPT_ID 
                left join
                    `""" + os.environ["WORKSPACE_CDR"] + """.visit_occurrence` v 
                        on observation.VISIT_OCCURRENCE_ID = v.VISIT_OCCURRENCE_ID 
                left join
                    `""" + os.environ["WORKSPACE_CDR"] + """.concept` o_visit 
                        on v.visit_concept_id = o_visit.concept_id"""

dataset_64469718_observation_df = pandas.read_gbq(dataset_64469718_observation_sql, dialect="standard", progress_bar_type="tqdm_notebook")

dataset_64469718_observation_df.head(5)

HBox(children=(FloatProgress(value=0.0, description='Downloading', max=689016.0, style=ProgressStyle(descriptiâ€¦

,VALUE_AS_STRING,OBSERVATION_DATETIME,PERSON_ID,VALUE_AS_NUMBER,UNIT_CONCEPT_NAME,VALUE_AS_CONCEPT_NAME,OBSERVATION_TYPE_CONCEPT_NAME,QUALIFIER_CONCEPT_NAME,STANDARD_CONCEPT_NAME,STANDARD_VOCABULARY,VISIT_OCCURRENCE_CONCEPT_NAME
0,cope_a_33,2020-07-31 17:19:21+00:00,1254882,NaN,No matching concept,Any other type of health insurance or health c...,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,None
1,373067005,2018-01-09 15:20:47+00:00,1390724,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,None
2,WhichDrugsUsed_MethamphetamineUse,2018-10-06 17:24:25+00:00,3099930,NaN,No matching concept,Which Drugs Used: Methamphetamine Use,Observation Recorded from a Survey,No matching concept,Recreational Drug Use: Which Drugs Used,PPI,None
3,LA15652-3,2017-07-27 16:20:10+00:00,2624005,NaN,No matching concept,Medicare,Observation Recorded from a Survey,No matching concept,Health Insurance: Health Insurance Type,PPI,None
4,LA18891-4,2019-02-09 19:09:10+00:00,1010198,NaN,No matching concept,Weekly,Observation Recorded from a Survey,No matching concept,Alcohol: 6 or More Drinks Occurrence,PPI,None

In [18]:
observation_df=dataset_64469718_observation_df

In [19]:
observation_df=janitor.clean_names(observation_df)

In [20]:
# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = observation_df   

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'observation_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
os.system(f"gsutil cp './{destination_filename}' '{my_bucket}/data/'")
print(f'[INFO] {destination_filename} is successfully uploaded in your bucket.')

[INFO] observation_df.csv is successfully uploaded in your bucket.

In [21]:
observation_df.sort_values('person_id').head(60)

,value_as_string,observation_datetime,person_id,value_as_number,unit_concept_name,value_as_concept_name,observation_type_concept_name,qualifier_concept_name,standard_concept_name,standard_vocabulary,visit_occurrence_concept_name
565902,AnnualIncome_50k75k,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,Annual Income: 50k 75k,Observation Recorded from a Survey,No matching concept,Total combined household income range in last ...,LOINC,None
269549,LA33-6,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,Yes,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,None
53102,LA18934-2,2018-09-25 16:03:16+00:00,1000042,NaN,No matching concept,Daily or almost daily,Observation Recorded from a Survey,No matching concept,Alcohol: 6 or More Drinks Occurrence,PPI,None
67647,LA32-8,2018-09-25 16:03:16+00:00,1000042,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Smoked at least 100 cigarettes in entire life,LOINC,None
616552,EmploymentStatus_GeneralizedEmployed,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,Employed for wages or self-employed,Observation Recorded from a Survey,No matching concept,Current occupational status [SAMHSA],LOINC,None
22747,3442003,2019-08-04 17:21:13+00:00,1000042,NaN,No matching concept,Better,Observation Recorded from a Survey,No matching concept,Insurance: Healthcare Coverage,PPI,None
405042,PMI_Skip,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Living Situation: Stable House Concern,PPI,None
573293,CurrentHomeOwn_Rent,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,Current Home Own: Rent,Observation Recorded from a Survey,No matching concept,Home Own: Current Home Own,PPI,None
89758,LA32-8,2018-09-25 16:03:16+00:00,1000042,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Hookah Smoking: Hookah Smoke Participant,PPI,None
405601,PMI_Skip,2018-09-25 16:00:49+00:00,1000042,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,How often have you been bothered by emotional ...,LOINC,None
377133,PMI_Skip,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Marital status,LOINC,None
70369,LA32-8,2018-09-25 16:03:16+00:00,1000042,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Electronic Smoking: Electric Smoke Participant,PPI,None
599854,WhatRaceEthnicity_Black,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,What Race Ethnicity: Black,Observation Recorded from a Survey,No matching concept,Race: What Race Ethnicity,PPI,None
372445,PMI_Skip,2018-09-25 16:03:16+00:00,1000042,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Health Insurance: Health Insurance Type,PPI,None
419091,473461003,2018-09-25 15:58:38+00:00,1000042,NaN,No matching concept,Educated to high school level,Observation Recorded from a Survey,No matching concept,What is the highest grade or level of schoolin...,LOINC,None
369098,PMI_Skip,2018-09-25 16:03:16+00:00,1000042,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Recreational Drug Use: Which Drugs Used,PPI,None
404677,PMI_Skip,2018-09-25 16:03:16+00:00,1000042,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Cigar Smoking: Cigar Smoke Participant,PPI,None
58562,LA32-8,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Living Situation: Stable House Concern,PPI,None
98092,LA32-8,2018-07-25 20:27:02+00:00,1000109,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Cigar Smoking: Cigar Smoke Participant,PPI,None
63120,LA32-8,2018-07-25 20:27:02+00:00,1000109,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Smoked at least 100 cigarettes in entire life,LOINC,None
422191,473461003,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,Educated to high school level,Observation Recorded from a Survey,No matching concept,What is the highest grade or level of schoolin...,LOINC,None
248884,LA33-6,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,Yes,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,None
572219,CurrentHomeOwn_Rent,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,Current Home Own: Rent,Observation Recorded from a Survey,No matching concept,Home Own: Current Home Own,PPI,None
607636,WhatRaceEthnicity_Hispanic,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,What Race Ethnicity: Hispanic,Observation Recorded from a Survey,No matching concept,Race: What Race Ethnicity,PPI,None
377097,PMI_Skip,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Total combined household income range in last ...,LOINC,None
188747,LA32-8,2018-07-25 20:27:02+00:00,1000109,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Electronic Smoking: Electric Smoke Participant,PPI,None
324152,LA51-8,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,Divorced,Observation Recorded from a Survey,No matching concept,Marital status,LOINC,None
451809,LA10082-8,2018-07-25 20:26:37+00:00,1000109,NaN,No matching concept,Sometimes,Observation Recorded from a Survey,No matching concept,How often have you been bothered by emotional ...,LOINC,None
662760,EmploymentStatus_GeneralizedNotEmployed,2018-07-25 20:22:37+00:00,1000109,NaN,No matching concept,Not currently employed for wages,Observation Recorded from a Survey,No matching concept,Current occupational status [SAMHSA],LOINC,None
189456,LA32-8,2018-07-25 20:27:02+00:00,1000109,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Hookah Smoking: Hookah Smoke Participant,PPI,None
400177,PMI_Skip,2018-07-25 20:27:02+00:00,1000109,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Health Insurance: Health Insurance Type,PPI,None
459533,LA14327-3,2018-07-25 20:27:02+00:00,1000109,NaN,No matching concept,None of these,Observation Recorded from a Survey,No matching concept,Recreational Drug Use: Which Drugs Used,PPI,None
426293,LA10044-8,2019-08-03 16:20:06+00:00,1000151,NaN,No matching concept,Often,Observation Recorded from a Survey,No matching concept,How often have you been bothered by emotional ...,LOINC,None
73377,LA32-8,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Living Situation: Stable House Concern,PPI,None
639813,6orMoreDrinksOccurence_NeverInLastYear,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,6 or More Drinks Occurrence: Never In Last Year,Observation Recorded from a Survey,No matching concept,Alcohol: 6 or More Drinks Occurrence,PPI,None
230983,LA33-6,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,Yes,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,None
226012,LA33-6,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,Yes,Observation Recorded from a Survey,No matching concept,Electronic Smoking: Electric Smoke Participant,PPI,None
405603,PMI_Skip,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Health Insurance: Health Insurance Type,PPI,None
564130,AnnualIncome_50k75k,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,Annual Income: 50k 75k,Observation Recorded from a Survey,No matching concept,Total combined household income range in last ...,LOINC,None
629483,WhichDrugsUsed_PrescriptionOpioidsUse,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,Which Drugs Used: Prescription Opioids Use,Observation Recorded from a Survey,No matching concept,Recreational Drug Use: Which Drugs Used,PPI,None
682543,HighestGrade_GeneralizedCollegeAndAbove,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,College graduate or advanced degree,Observation Recorded from a Survey,No matching concept,What is the highest grade or level of schoolin...,LOINC,None
665758,EmploymentStatus_GeneralizedNotEmployed,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,Not currently employed for wages,Observation Recorded from a Survey,No matching concept,Current occupational status [SAMHSA],LOINC,None
306184,LA47-6,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,Never married,Observation Recorded from a Survey,No matching concept,Marital status,LOINC,None
415,WhichDrugsUsed_PrescriptionStimulantsUse,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,Which Drugs Used: Prescription Stimulants Use,Observation Recorded from a Survey,No matching concept,Recreational Drug Use: Which Drugs Used,PPI,None
592975,WhatRaceEthnicity_Black,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,What Race Ethnicity: Black,Observation Recorded from a Survey,No matching concept,Race: What Race Ethnicity,PPI,None
83096,LA32-8,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Hookah Smoking: Hookah Smoke Participant,PPI,None
554444,CurrentHomeOwn_Own,2019-08-03 16:15:51+00:00,1000151,NaN,No matching concept,Current Home Own: Own,Observation Recorded from a Survey,No matching concept,Home Own: Current Home Own,PPI,None
246199,LA33-6,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,Yes,Observation Recorded from a Survey,No matching concept,Smoked at least 100 cigarettes in entire life,LOINC,None
264376,LA33-6,2019-08-03 16:24:04+00:00,1000151,NaN,No matching concept,Yes,Observation Recorded from a Survey,No matching concept,Cigar Smoking: Cigar Smoke Participant,PPI,None
635526,6orMoreDrinksOccurence_NeverInLastYear,2018-07-28 17:14:09+00:00,1000185,NaN,No matching concept,6 or More Drinks Occurrence: Never In Last Year,Observation Recorded from a Survey,No matching concept,Alcohol: 6 or More Drinks Occurrence,PPI,None
464374,LA14327-3,2018-07-28 17:14:09+00:00,1000185,NaN,No matching concept,None of these,Observation Recorded from a Survey,No matching concept,Recreational Drug Use: Which Drugs Used,PPI,None
315460,LA48-4,2018-07-27 12:50:06+00:00,1000185,NaN,No matching concept,Married,Observation Recorded from a Survey,No matching concept,Marital status,LOINC,None
77164,LA32-8,2018-07-28 17:14:09+00:00,1000185,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Hookah Smoking: Hookah Smoke Participant,PPI,None
435800,LA10066-1,2018-07-28 17:08:21+00:00,1000185,NaN,No matching concept,Rarely,Observation Recorded from a Survey,No matching concept,How often have you been bothered by emotional ...,LOINC,None
374020,PMI_Skip,2018-07-28 17:14:09+00:00,1000185,NaN,No matching concept,PMI: Skip,Observation Recorded from a Survey,No matching concept,Health Insurance: Health Insurance Type,PPI,None
682857,HighestGrade_GeneralizedCollegeAndAbove,2018-07-27 12:50:06+00:00,1000185,NaN,No matching concept,College graduate or advanced degree,Observation Recorded from a Survey,No matching concept,What is the highest grade or level of schoolin...,LOINC,None
544396,CurrentHomeOwn_Own,2018-07-27 12:50:06+00:00,1000185,NaN,No matching concept,Current Home Own: Own,Observation Recorded from a Survey,No matching concept,Home Own: Current Home Own,PPI,None
119328,LA32-8,2018-07-28 17:14:09+00:00,1000185,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Cigar Smoking: Cigar Smoke Participant,PPI,None
334548,LA4457-3,2018-07-27 12:50:06+00:00,1000185,NaN,No matching concept,White,Observation Recorded from a Survey,No matching concept,Race: What Race Ethnicity,PPI,None
277731,LA33-6,2018-07-27 12:50:06+00:00,1000185,NaN,No matching concept,Yes,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,None

In [22]:
import pandas
import os

# This query represents dataset "Asthma_exacerb_predict" for domain "survey" and was generated for All of Us Registered Tier Dataset v4
dataset_64469718_survey_sql = """
    SELECT
        answer.question,
        answer.answer,
        answer.survey_datetime,
        answer.person_id,
        answer.survey  
    FROM
        `""" + os.environ["WORKSPACE_CDR"] + """.ds_survey` answer   
    WHERE
        (
            question_concept_id in (
                43528873, 43530546, 43530388
            )
        )  
        AND (
            answer.PERSON_ID IN (
                select
                    person_id  
                from
                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
                where
                    cb_search_person.person_id in (
                        select
                            criteria.person_id 
                        from
                            (select
                                distinct person_id,
                                entry_date,
                                concept_id 
                            from
                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                            where
                                person_id in (
                                    select
                                        person_id 
                                    from
                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                    where
                                        is_standard = 1 
                                        and concept_id in (
                                            select
                                                distinct c.concept_id 
                                            from
                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                            join
                                                (
                                                    select
                                                        cast(cr.id as string) as id 
                                                    from
                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                    where
                                                        domain_id = 'CONDITION' 
                                                        and is_standard = 1 
                                                        and concept_id in (764949, 46274062, 4271333, 46270573, 4146581, 46273487, 46270028, 45768963, 42539549, 46269770, 4142738, 45768910, 443801, 4145356, 4152913, 45769350, 46273454, 4279553, 45769443, 317009, 314754, 4138760, 252946, 46269783, 46269790, 252658, 46269786, 45768965, 4051466, 46273462, 4245676, 252942, 4215802, 45772937, 40481763, 37108581, 4075237, 256448, 46269802, 4141978, 764677, 46270322, 4125022, 46269776, 45768964, 4233784, 4155468, 37310241, 46273635, 4207479, 4123253, 45769352, 4143828, 42535716, 257581, 46273452, 45771045, 46269778, 312950, 45769351, 4309833, 45768911, 36684328, 4308356, 313236, 46269789, 45768912, 761844, 42536208, 4145497, 4312524, 46270030, 46269787, 40483397, 45769438, 45769441, 43530693, 45773005, 4206340, 45766728, 4194289, 46270082, 45769442, 42538744, 4191479, 46269784, 4155469, 37116845) 
                                                        and is_selectable = 1 
                                                        and full_text like '%[condition_rank1]%'
                                                ) a 
                                                    on (
                                                        c.path like concat('%.',
                                                    a.id,
                                                    '.%') 
                                                    or c.path like concat('%.',
                                                    a.id) 
                                                    or c.path like concat(a.id,
                                                    '.%')) 
                                                where
                                                    domain_id = 'CONDITION' 
                                                    and is_standard = 1 
                                                    and is_selectable = 1
                                                )
                                            union
                                            all select
                                                person_id 
                                            from
                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                                            where
                                                is_standard = 0 
                                                and concept_id in (
                                                    select
                                                        distinct c.concept_id 
                                                    from
                                                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                                                    join
                                                        (
                                                            select
                                                                cast(cr.id as string) as id 
                                                            from
                                                                `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr 
                                                            where
                                                                domain_id = 'CONDITION' 
                                                                and is_standard = 0 
                                                                and concept_id in (46270322, 4155468, 46269789, 45572168, 45768965, 313236, 45768911, 4207479, 46273454, 44820889, 46270573, 44834769, 45601133, 45771045, 46269802, 4194289, 45567266, 44824288, 1569490, 45768912, 44829012, 4215802, 46269784, 44821988, 46270030, 42539549, 312950, 46269786, 764949, 4051466, 4245676, 45543269, 45543270, 45557626, 45769351, 4143828, 4152913, 45769442, 46273635, 45772937, 45548117, 4191479, 44832423, 4125022, 44833611, 45591559, 45576951, 4271333, 317009, 37310241, 4206340, 45548116, 45572170, 45562457, 4146581, 4123253, 256448, 46269776, 45768964, 46269787, 46273452, 44823144, 4312524, 4279553, 43530693, 42535716, 44830115, 46273487, 45769438, 4138760, 4155469, 36684328, 44831280, 1569491, 46269770, 40483397, 1569488, 44831278, 45576952, 45567265, 44824289, 44826679, 4141978, 45601134, 4145356, 43530700, 45773005, 4144757, 45581859, 45769441, 46269778, 4309833, 46269783, 4142738, 44831279, 4308356, 37116845, 44832424, 45581860, 257581, 44828510, 45768963, 764677, 44837136, 252658, 4145497, 46270028, 1569489, 46269790, 46273462, 45766728, 46270082, 44837135, 42536208, 42538744, 45768910, 37108581, 44821987, 35225323, 314754, 45586675, 40410639, 44824287, 761844, 45769352, 4075237, 45591558, 443801, 45572169, 45572171, 46274062, 4233784) 
                                                                and is_selectable = 1 
                                                                and full_text like '%[condition_rank1]%'
                                                        ) a 
                                                            on (
                                                                c.path like concat('%.',
                                                            a.id,
                                                            '.%') 
                                                            or c.path like concat('%.',
                                                            a.id) 
                                                            or c.path like concat(a.id,
                                                            '.%')) 
                                                        where
                                                            domain_id = 'CONDITION' 
                                                            and is_standard = 0 
                                                            and is_selectable = 1
                                                        )
                                                )
                                            ) criteria 
                                    ) 
                            )
                        )"""

dataset_64469718_survey_df = pandas.read_gbq(dataset_64469718_survey_sql, dialect="standard", progress_bar_type="tqdm_notebook")

dataset_64469718_survey_df.head(5)

HBox(children=(FloatProgress(value=0.0, description='Downloading', max=22601.0, style=ProgressStyle(descriptioâ€¦

,question,answer,survey_datetime,person_id,survey
0,Respiratory: Rx Meds for Asthma,PMI: Skip,2019-08-22 22:28:11+00:00,1755452,Personal Medical History
1,Respiratory: Rx Meds for Asthma,PMI: Skip,2019-02-22 18:57:38+00:00,2868687,Personal Medical History
2,Respiratory: How Old Were You Asthma,PMI: Skip,2018-05-06 23:14:27+00:00,1170568,Personal Medical History
3,Respiratory: How Old Were You Asthma,How Old Were You Asthma: Elderly,2019-03-06 02:08:07+00:00,1471184,Personal Medical History
4,Respiratory: How Old Were You Asthma,How Old Were You Asthma: Elderly,2019-04-29 19:58:59+00:00,1669567,Personal Medical History

In [23]:
survey_df=dataset_64469718_survey_df

In [24]:
survey_df=janitor.clean_names(survey_df)

In [25]:
# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = survey_df   

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'survey_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
os.system(f"gsutil cp './{destination_filename}' '{my_bucket}/data/'")
print(f'[INFO] {destination_filename} is successfully uploaded in your bucket.')

[INFO] survey_df.csv is successfully uploaded in your bucket.

In [ ]:
survey_df.info()

In [ ]:
survey_df.sort_values('person_id').head(60)

# Merging the data frames

In [10]:
# This snippet assumes you run setup first

# This code copies file in your Google Bucket and loads it into a dataframe

# Replace 'test.csv' with THE NAME of the file you're going to download from the bucket (don't delete the quotation marks)
name_of_file_in_bucket = 'person_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
my_dataframe = pd.read_csv(name_of_file_in_bucket)
my_dataframe.head()

[INFO] person_df.csv is successfully downloaded into your working space

,date_of_birth,person_id,race,gender,ethnicity,sex_at_birth
0,1970-12-31 00:00:00+00:00,1222795,None of these,Male,What Race Ethnicity: Race Ethnicity None Of These,No matching concept
1,1950-12-07 00:00:00+00:00,3194246,None of these,Female,What Race Ethnicity: Race Ethnicity None Of These,No matching concept
2,1960-09-03 00:00:00+00:00,1198242,I prefer not to answer,"Not man only, not woman only, prefer not to an...",PMI: Prefer Not To Answer,No matching concept
3,1987-06-22 00:00:00+00:00,1077946,PMI: Skip,"Not man only, not woman only, prefer not to an...",PMI: Skip,No matching concept
4,1950-12-22 00:00:00+00:00,1289088,PMI: Skip,"Not man only, not woman only, prefer not to an...",PMI: Skip,No matching concept

In [3]:
# This snippet assumes you run setup first

# This code copies file in your Google Bucket and loads it into a dataframe

# Replace 'test.csv' with THE NAME of the file you're going to download from the bucket (don't delete the quotation marks)
name_of_file_in_bucket = 'condition_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
my_dataframe = pd.read_csv(name_of_file_in_bucket)
my_dataframe.head()

[INFO] condition_df.csv is successfully downloaded into your working space

,condition_start_datetime,condition_end_datetime,stop_reason,person_id,condition_type_concept_name,condition_status_concept_name,standard_concept_name,standard_vocabulary,visit_occurrence_concept_name
0,2016-08-21 00:00:00+00:00,NaN,NaN,3347059,No matching concept,NaN,Uncomplicated asthma,SNOMED,NaN
1,2011-11-11 05:00:00+00:00,2011-11-11 05:00:00+00:00,NaN,1284243,EHR billing diagnosis,Final diagnosis,Asthma,SNOMED,NaN
2,2008-04-21 05:00:00+00:00,2008-04-21 00:00:00+00:00,NaN,2940808,Secondary Condition,Final diagnosis,Acute severe refractory exacerbation of asthma,SNOMED,NaN
3,2014-07-21 05:00:00+00:00,2014-07-21 05:00:00+00:00,NaN,1784187,Primary Condition,Final diagnosis,Acute exacerbation of asthma,SNOMED,NaN
4,2017-04-08 00:00:00+00:00,NaN,NaN,2032144,Patient Self-Reported Condition,No matching concept,Wheezing,SNOMED,NaN

In [4]:
# This snippet assumes you run setup first

# This code copies file in your Google Bucket and loads it into a dataframe

# Replace 'test.csv' with THE NAME of the file you're going to download from the bucket (don't delete the quotation marks)
name_of_file_in_bucket = 'measurement_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
my_dataframe = pd.read_csv(name_of_file_in_bucket)
my_dataframe.head()

[INFO] measurement_df.csv is successfully downloaded into your working space

,range_high,range_low,measurement_datetime,person_id,value_as_number,value_as_concept_name,measurement_type_concept_name,standard_concept_name,standard_vocabulary,visit_occurrence_concept_name
0,1.035,1.001,2017-07-24 05:01:00+00:00,2627490,1.019,No matching concept,Lab result,Specific gravity of Urine by Test strip,LOINC,NaN
1,1.900,0.830,2016-12-28 07:35:00+00:00,1144394,0.850,NaN,Lab result,Thyroxine (T4) free [Mass/volume] in Serum or ...,LOINC,NaN
2,NaN,NaN,2019-07-19 01:07:00+00:00,3413544,0.200,NaN,Lab result,Urobilinogen [Mass/volume] in Urine by Test strip,LOINC,NaN
3,305.000,278.000,2016-09-14 19:07:00+00:00,1035182,295.000,No matching concept,Lab result,Osmolality of Serum or Plasma,LOINC,NaN
4,NaN,NaN,2018-01-26 13:21:00+00:00,1940125,NaN,Negative,Lab result,Glucose [Mass/volume] in Urine,LOINC,NaN

In [6]:
# This snippet assumes you run setup first

# This code copies file in your Google Bucket and loads it into a dataframe

# Replace 'test.csv' with THE NAME of the file you're going to download from the bucket (don't delete the quotation marks)
name_of_file_in_bucket = 'drug_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
my_dataframe = pd.read_csv(name_of_file_in_bucket)
my_dataframe.head()

[INFO] drug_df.csv is successfully downloaded into your working space

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.

,person_id,drug_exposure_start_datetime,verbatim_end_date,refills,days_supply,quantity,stop_reason,drug_exposure_end_datetime,route_concept_name,drug_type_concept_name,standard_concept_name,standard_vocabulary,source_concept_name,visit_occurrence_concept_name
0,2620809,2016-07-09 05:00:00+00:00,NaN,NaN,0.0,0.0,NaN,NaN,No matching concept,Prescription dispensed in pharmacy,phenobarbital 130 MG/ML Injectable Solution,RxNorm,phenobarbital 130 MG/ML Injectable Solution,NaN
1,2443991,2016-05-21 05:00:00+00:00,NaN,NaN,0.0,0.0,NaN,NaN,No matching concept,Prescription dispensed in pharmacy,10 ML atropine sulfate 0.1 MG/ML Prefilled Syr...,RxNorm,10 ML atropine sulfate 0.1 MG/ML Prefilled Syr...,NaN
2,3258214,2016-10-22 05:00:00+00:00,NaN,NaN,30.0,30.0,NaN,NaN,Oral,Prescription dispensed in pharmacy,montelukast 10 MG Oral Tablet,RxNorm,montelukast 10 MG Oral Tablet,NaN
3,2078640,2018-07-02 07:17:31+00:00,NaN,NaN,30.0,1.0,NaN,2018-08-01 07:17:31+00:00,Inhalation,Prescription dispensed in pharmacy,120 ACTUAT budesonide 0.08 MG/ACTUAT / formote...,RxNorm,120 ACTUAT budesonide 0.08 MG/ACTUAT / formote...,NaN
4,2807206,2014-08-22 05:00:00+00:00,NaN,NaN,6.0,21.0,NaN,NaN,Oral,Prescription dispensed in pharmacy,{21 (methylprednisolone 4 MG Oral Tablet) } Pack,RxNorm,{21 (methylprednisolone 4 MG Oral Tablet) } Pack,NaN

In [7]:
# This snippet assumes you run setup first

# This code copies file in your Google Bucket and loads it into a dataframe

# Replace 'test.csv' with THE NAME of the file you're going to download from the bucket (don't delete the quotation marks)
name_of_file_in_bucket = 'survey_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
my_dataframe = pd.read_csv(name_of_file_in_bucket)
my_dataframe.head()

[INFO] survey_df.csv is successfully downloaded into your working space

,question,answer,survey_datetime,person_id,survey
0,Respiratory: Rx Meds for Asthma,PMI: Skip,2019-08-22 22:28:11+00:00,1755452,Personal Medical History
1,Respiratory: Rx Meds for Asthma,PMI: Skip,2019-02-22 18:57:38+00:00,2868687,Personal Medical History
2,Respiratory: How Old Were You Asthma,PMI: Skip,2018-05-06 23:14:27+00:00,1170568,Personal Medical History
3,Respiratory: How Old Were You Asthma,How Old Were You Asthma: Elderly,2019-03-06 02:08:07+00:00,1471184,Personal Medical History
4,Respiratory: How Old Were You Asthma,How Old Were You Asthma: Elderly,2019-04-29 19:58:59+00:00,1669567,Personal Medical History

In [8]:
# This snippet assumes you run setup first

# This code copies file in your Google Bucket and loads it into a dataframe

# Replace 'test.csv' with THE NAME of the file you're going to download from the bucket (don't delete the quotation marks)
name_of_file_in_bucket = 'observation_df.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
my_dataframe = pd.read_csv(name_of_file_in_bucket)
my_dataframe.head()

[INFO] observation_df.csv is successfully downloaded into your working space

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.

,value_as_string,observation_datetime,person_id,value_as_number,unit_concept_name,value_as_concept_name,observation_type_concept_name,qualifier_concept_name,standard_concept_name,standard_vocabulary,visit_occurrence_concept_name
0,cope_a_33,2020-07-31 17:19:21+00:00,1254882,NaN,No matching concept,Any other type of health insurance or health c...,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,NaN
1,373067005,2018-01-09 15:20:47+00:00,1390724,NaN,No matching concept,No,Observation Recorded from a Survey,No matching concept,Are you covered by health insurance or some ot...,LOINC,NaN
2,WhichDrugsUsed_MethamphetamineUse,2018-10-06 17:24:25+00:00,3099930,NaN,No matching concept,Which Drugs Used: Methamphetamine Use,Observation Recorded from a Survey,No matching concept,Recreational Drug Use: Which Drugs Used,PPI,NaN
3,LA15652-3,2017-07-27 16:20:10+00:00,2624005,NaN,No matching concept,Medicare,Observation Recorded from a Survey,No matching concept,Health Insurance: Health Insurance Type,PPI,NaN
4,LA18891-4,2019-02-09 19:09:10+00:00,1010198,NaN,No matching concept,Weekly,Observation Recorded from a Survey,No matching concept,Alcohol: 6 or More Drinks Occurrence,PPI,NaN

In [1]:
import pandas as pd
person_df=pd.read_csv('person_df.csv')
condition_df=pd.read_csv('condition_df.csv')
measurement_df=pd.read_csv('measurement_df.csv')
drug_df=pd.read_csv('drug_df.csv')
survey_df=pd.read_csv('survey_df.csv')
observation_df=pd.read_csv('observation_df.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
measurement_df.head(60).sort_values('person_id')

,range_high,range_low,measurement_datetime,person_id,value_as_number,value_as_concept_name,measurement_type_concept_name,standard_concept_name,standard_vocabulary,visit_occurrence_concept_name
3,305.000,278.000,2016-09-14 19:07:00+00:00,1035182,295.000,No matching concept,Lab result,Osmolality of Serum or Plasma,LOINC,NaN
40,NaN,NaN,2012-04-17 08:41:00+00:00,1066943,100.000,NaN,Lab result,Glucose [Mass/volume] in Venous blood,LOINC,NaN
33,1.000,0.200,2019-02-08 19:06:00+00:00,1117263,0.200,NaN,Lab result,Urobilinogen [Mass/volume] in Urine by Test strip,LOINC,NaN
52,1.240,0.700,2015-01-12 18:48:00+00:00,1126457,0.900,NaN,Lab result,Thyroxine (T4) free [Mass/volume] in Serum or ...,LOINC,NaN
1,1.900,0.830,2016-12-28 07:35:00+00:00,1144394,0.850,NaN,Lab result,Thyroxine (T4) free [Mass/volume] in Serum or ...,LOINC,NaN
36,8.000,5.000,2019-04-29 19:11:00+00:00,1168277,6.500,NaN,Lab result,pH of Urine,LOINC,NaN
6,NaN,NaN,2015-03-21 05:00:00+00:00,1168396,NaN,Negative,Lab result,Protein [Mass/volume] in Urine by Test strip,LOINC,NaN
22,NaN,NaN,2019-06-16 16:40:00+00:00,1266318,NaN,Small,Lab result,Hemoglobin [Presence] in Urine by Test strip,LOINC,NaN
54,NaN,NaN,2015-12-03 05:00:00+00:00,1285309,NaN,Negative,Lab result,Protein [Mass/volume] in Urine by Test strip,LOINC,NaN
51,1.000,0.100,2007-09-30 14:45:46+00:00,1336304,0.200,No matching concept,Lab result,Urobilinogen [Mass/volume] in Urine by Test strip,LOINC,NaN
28,NaN,NaN,2018-11-24 09:35:00+00:00,1346402,30.000,No matching concept,Lab result,Protein [Mass/volume] in Urine by Test strip,LOINC,NaN
46,99.000,95.000,2015-04-15 20:30:00+00:00,1348803,98.200,NaN,Lab result,Oxygen saturation in Arterial blood,LOINC,NaN
9,NaN,NaN,2020-06-23 12:48:00+00:00,1396230,99.000,No matching concept,Lab result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,NaN
21,NaN,NaN,2007-12-04 05:00:00+00:00,1440786,NaN,Small,Lab result,Hemoglobin [Presence] in Urine by Test strip,LOINC,NaN
57,NaN,NaN,2018-12-12 07:20:00+00:00,1475692,NaN,Negative,Lab result,Protein [Mass/volume] in Urine by Test strip,LOINC,NaN
17,170.000,37.000,2016-03-14 00:21:00+00:00,1547305,57.000,No matching concept,Lab result,Iron [Mass/volume] in Serum or Plasma,LOINC,NaN
10,NaN,NaN,2007-11-17 17:01:00+00:00,1549380,38.000,No matching concept,Lab result,Cholesterol in HDL [Mass/volume] in Serum or P...,LOINC,NaN
49,NaN,NaN,2013-08-11 04:00:00+00:00,1592326,60.000,NaN,Lab result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,NaN
7,NaN,NaN,2011-01-01 10:57:59+00:00,1606569,10.000,No matching concept,Lab observation numeric result,Protein [Mass/volume] in Urine by Test strip,LOINC,NaN
38,NaN,NaN,2018-11-25 17:26:00+00:00,1623789,95.000,No matching concept,Lab result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,NaN
37,NaN,NaN,2020-03-09 16:31:00+00:00,1654747,NaN,Negative,Lab result,Glucose [Mass/volume] in Urine by Test strip,LOINC,NaN
12,NaN,NaN,2005-05-17 07:31:23+00:00,1670968,30.000,No matching concept,Lab observation numeric result,Protein [Mass/volume] in Urine by Test strip,LOINC,NaN
31,NaN,NaN,2018-01-08 05:00:00+00:00,1686411,NaN,Negative,Lab result,Protein [Mass/volume] in Urine by Test strip,LOINC,NaN
48,NaN,NaN,2013-08-25 20:11:00+00:00,1795336,191.000,No matching concept,Lab result,Cobalamin (Vitamin B12) [Mass/volume] in Serum...,LOINC,NaN
11,8.000,5.000,2017-08-23 19:57:00+00:00,1919119,6.000,NaN,Lab result,pH of Urine,LOINC,NaN
53,NaN,39.000,2009-05-21 13:47:21+00:00,1931256,49.000,No matching concept,Lab observation numeric result,Cholesterol in HDL [Mass/volume] in Serum or P...,LOINC,NaN
4,NaN,NaN,2018-01-26 13:21:00+00:00,1940125,NaN,Negative,Lab result,Glucose [Mass/volume] in Urine,LOINC,NaN
19,NaN,NaN,2012-01-24 13:12:00.050000+00:00,1954235,7.000,NaN,Lab result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,NaN
5,NaN,NaN,2018-05-25 23:59:00+00:00,1954563,NaN,No matching concept,Lab result,Hemoglobin [Presence] in Urine by Automated te...,LOINC,NaN
39,NaN,40.000,2009-04-24 07:17:50+00:00,1990917,31.000,No matching concept,Lab observation numeric result,Cholesterol in HDL [Mass/volume] in Serum or P...,LOINC,NaN
27,0.800,0.100,2016-10-30 05:00:00+00:00,2054345,NaN,0.2,Lab result,Bilirubin.indirect [Mass/volume] in Serum or P...,LOINC,NaN
35,8.000,5.000,2011-11-19 06:13:00+00:00,2063791,7.000,NaN,Lab result,pH of Urine,LOINC,NaN
47,17.800,14.000,2017-09-24 01:56:45+00:00,2109274,13.900,NaN,Lab result,Hemoglobin [Mass/volume] in Venous blood,LOINC,NaN
32,158.000,23.000,2019-05-11 08:30:00+00:00,2179791,76.000,No matching concept,Lab observation numeric result,Triglyceride [Mass/volume] in Serum or Plasma,LOINC,NaN
29,NaN,NaN,2017-12-20 15:18:00+00:00,2199030,11.400,NaN,Lab result,Folate [Mass/volume] in Serum or Plasma,LOINC,NaN
13,NaN,NaN,2016-02-20 09:29:00+00:00,2201312,9.000,NaN,Lab result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,NaN
50,NaN,NaN,2018-03-29 11:33:00+00:00,2421735,0.100,NaN,Lab result,Choriogonadotropin.beta subunit [Units/volume]...,LOINC,NaN
18,8.000,5.000,2018-09-22 17:48:00+00:00,2428354,NaN,No matching concept,Lab result,pH of Urine by Test strip,LOINC,NaN
45,NaN,NaN,2013-06-05 20:00:00+00:00,2436306,NaN,2+,Lab result,Hemoglobin [Presence] in Urine by Automated te...,LOINC,NaN
43,4.900,0.000,2016-06-09 13:40:00.517000+00:00,2465411,2.300,NaN,Lab result,Cholesterol.total/Cholesterol in HDL [Mass Rat...,LOINC,NaN
42,199.000,0.000,2018-04-15 11:04:04+00:00,2475664,300.000,No matching concept,Lab observation numeric result,Triglyceride [Mass/volume] in Serum or Plasma,LOINC,NaN
58,1.030,1.001,2018-09-04 13:17:48+00:00,2535344,1.021,No matching concept,Lab observation numeric result,Specific gravity of Urine by Test strip,LOINC,NaN
20,NaN,NaN,2019-04-12 11:18:00+00:00,2579915,45.000,No matching concept,Lab result,Glomerular filtration rate/1.73 sq M.predicted...,LOINC,NaN
0,1.035,1.001,2017-07-24 05:01:00+00:00,2627490,1.019,No matching concept,Lab result,Specific gravity of Urine by Test strip,LOINC,NaN
23,NaN,NaN,2012-10-30 08:00:00+00:00,2803675,30.000,No matching concept,Lab result,Lipase [Enzymatic activity/volume] in Serum or...,LOINC,NaN
15,NaN,NaN,2019-02-09 17:42:00+00:00,2982751,0.200,NaN,Lab result,Urobilinogen [Mass/volume] in Urine by Test strip,LOINC,NaN
56,8.000,5.000,2017-07-22 17:59:00+00:00,2986488,5.500,NaN,Lab result,pH of Urine,LOINC,NaN
59,NaN,NaN,2008-12-04 16:50:00+00:00,2987048,30.000,NaN,Lab result,Protein [Mass/volume] in Urine by Automated te...,LOINC,NaN
24,NaN,NaN,2017-09-06 06:25:00+00:00,3000010,NaN,No matching concept,Lab result,Protein [Presence] in Urine by Test strip,LOINC,NaN
44,1.590,0.950,2006-10-22 12:12:50+00:00,3010176,0.900,No matching concept,Lab observation numeric result,Albumin/Globulin [Mass Ratio] in Serum or Plasma,LOINC,NaN
30,60.000,40.000,2017-11-02 23:39:39+00:00,3018299,29.000,NaN,Lab result,Cholesterol in HDL [Mass/volume] in Serum or P...,LOINC,NaN
8,45.000,40.000,2016-05-28 07:37:00+00:00,3039087,51.000,NaN,Lab result,Carbon dioxide [Partial pressure] adjusted to ...,LOINC,NaN
26,5.700,0.700,2014-11-23 16:49:00+00:00,3058534,8.424,No matching concept,Lab result,Thyrotropin [Units/volume] in Serum or Plasma,LOINC,NaN
41,NaN,NaN,2012-04-19 22:44:00+00:00,3077712,53.000,No matching concept,Lab result,Cholesterol in HDL [Mass/volume] in Serum or P...,LOINC,NaN
55,NaN,NaN,2012-09-11 17:28:00+00:00,3117883,0.000,Positive,Lab result,Nitrite [Mass/volume] in Urine by Test strip,LOINC,NaN
14,40.000,10.000,2017-10-05 12:30:00+00:00,3373348,17.000,No matching concept,Lab result,Alanine aminotransferase [Enzymatic activity/v...,LOINC,NaN
2,NaN,NaN,2019-07-19 01:07:00+00:00,3413544,0.200,NaN,Lab result,Urobilinogen [Mass/volume] in Urine by Test strip,LOINC,NaN
25,146.000,136.000,2014-03-13 09:35:00+00:00,3455722,129.000,No matching concept,Lab result,Sodium [Moles/volume] in Blood,LOINC,NaN
16,59.000,40.000,2012-01-14 13:43:00.740000+00:00,3472539,48.000,NaN,Lab result,Cholesterol in HDL [Mass/volume] in Serum or P...,LOINC,NaN
34,146.000,136.000,2011-06-30 14:56:00+00:00,3512728,143.000,No matching concept,Lab result,Sodium [Moles/volume] in Blood,LOINC,NaN

In [4]:
measurement_df=measurement_df.drop(columns=['range_high','range_low','value_as_concept_name',
                             'measurement_type_concept_name', 'standard_vocabulary',
                             'visit_occurrence_concept_name'])

,measurement_datetime,person_id,value_as_number,standard_concept_name
0,2017-07-24 05:01:00+00:00,2627490,1.019,Specific gravity of Urine by Test strip
1,2016-12-28 07:35:00+00:00,1144394,0.850,Thyroxine (T4) free [Mass/volume] in Serum or ...
2,2019-07-19 01:07:00+00:00,3413544,0.200,Urobilinogen [Mass/volume] in Urine by Test strip
3,2016-09-14 19:07:00+00:00,1035182,295.000,Osmolality of Serum or Plasma
4,2018-01-26 13:21:00+00:00,1940125,NaN,Glucose [Mass/volume] in Urine
...,...,...,...,...
41504273,2019-04-27 00:06:02+00:00,2393893,144.030,Glomerular filtration rate/1.73 sq M.predicted...
41504274,2017-12-03 06:09:00+00:00,2261920,62.000,Glomerular filtration rate/1.73 sq M.predicted...
41504275,2012-11-15 17:59:00+00:00,2716510,NaN,Glomerular filtration rate/1.73 sq M.predicted...
41504276,2012-09-23 17:31:00+00:00,2678761,NaN,Glomerular filtration rate/1.73 sq M.predicted...
41504277,2015-04-16 22:41:00+00:00,1478655,78.950,Glomerular filtration rate/1.73 sq M.predicted...

In [16]:
measurement_df.sort_values('person_id').tail(60)

,measurement_datetime,person_id,value_as_number,standard_concept_name
20132732,2017-07-17 10:04:00+00:00,3524669,1.90,Eosinophils/100 leukocytes in Blood by Automat...
25630536,2013-07-17 03:08:00+00:00,3524669,0.70,Bilirubin direct and total panel [Mass/volume]...
26623967,2016-07-17 09:04:00+00:00,3524669,32.90,MCHC [Mass/volume] by Automated count
24555974,2010-07-17 09:02:00+00:00,3524669,39.00,Hematocrit [Volume Fraction] of Blood by Autom...
13202668,2017-07-17 11:12:00+00:00,3524669,63.00,Cholesterol in VLDL [Mass/volume] in Serum or ...
9081009,2011-07-17 10:10:00+00:00,3524669,54.00,Cholesterol in HDL [Mass/volume] in Serum or P...
30869847,2019-07-17 09:03:00+00:00,3524669,104.30,MCV [Entitic volume] by Automated count
17311784,2017-07-17 13:04:00+00:00,3524669,336.00,Kappa light chains [Mass/volume] in Serum or P...
29529787,2019-07-17 10:03:00+00:00,3524669,3.20,Globulin [Mass/volume] in Serum by calculation
11693204,2018-07-17 09:03:00+00:00,3524669,3.46,Erythrocytes [#/volume] in Blood by Automated ...
34903263,2017-07-17 09:05:00+00:00,3524669,30.40,MCHC [Mass/volume] by Automated count
6530967,2019-07-17 10:05:00+00:00,3524669,106.00,Chloride [Moles/volume] in Serum or Plasma
21466690,2017-07-17 10:07:00+00:00,3524669,21.00,Urea nitrogen/Creatinine [Mass Ratio] in Serum...
29529791,2017-07-17 11:01:00+00:00,3524669,3.80,Globulin [Mass/volume] in Serum by calculation
28509386,2017-07-17 12:11:00+00:00,3524669,29.10,Lymphocytes/100 leukocytes in Blood by Automat...
11957938,2015-07-17 13:09:00+00:00,3524669,64.00,Neutrophils/100 leukocytes in Blood by Automat...
21466689,2018-07-17 11:09:00+00:00,3524669,20.90,Urea nitrogen/Creatinine [Mass Ratio] in Serum...
9885750,2016-07-17 02:03:00+00:00,3524669,10.80,Hemoglobin [Mass/volume] in Blood
15994735,2017-07-17 10:05:00+00:00,3524669,2.90,Eosinophils/100 leukocytes in Blood by Automat...
4915137,2014-07-17 13:10:00+00:00,3524669,27.00,Gamma glutamyl transferase [Enzymatic activity...
17953871,2018-07-17 11:12:00+00:00,3524669,17.00,Anion gap in Serum or Plasma
15869119,2015-07-17 10:05:00+00:00,3524669,0.30,Basophils/100 leukocytes in Blood by Automated...
15415701,2017-07-17 13:09:00+00:00,3524669,0.44,Monocytes [#/volume] in Blood by Automated count
37997513,2017-07-17 11:12:00+00:00,3524669,1.07,Thyrotropin [Units/volume] in Serum or Plasma
29830968,2017-07-17 10:07:00+00:00,3524669,0.90,Albumin/Globulin [Mass Ratio] in Serum or Plasma
33782847,2010-07-17 09:06:00+00:00,3524669,1.00,Creatinine [Mass/volume] in Blood
39412563,2015-07-17 13:10:00+00:00,3524669,111.00,Glucose [Mass/volume] in Serum or Plasma
32493482,2017-07-17 09:10:00+00:00,3524669,0.50,Basophils/100 leukocytes in Blood by Automated...
36693279,2018-07-17 09:05:00+00:00,3524669,6.10,Monocytes/100 leukocytes in Blood by Automated...
36693274,2014-07-17 09:05:00+00:00,3524669,8.00,Monocytes/100 leukocytes in Blood by Automated...
24179530,2017-07-17 10:06:00+00:00,3524669,0.60,Basophils/100 leukocytes in Blood by Automated...
3992085,2018-07-17 10:02:00+00:00,3524669,55.00,Alkaline phosphatase [Enzymatic activity/volum...
12303169,2019-07-17 09:06:00+00:00,3524669,60.00,Alkaline phosphatase [Enzymatic activity/volum...
10041625,2017-07-17 10:11:00+00:00,3524669,31.70,MCHC [Mass/volume] by Automated count
15626035,2016-07-17 03:05:00+00:00,3524669,0.20,Eosinophils [#/volume] in Blood by Automated c...
39073569,2018-07-17 09:01:00+00:00,3524669,33.20,MCHC [Mass/volume] by Automated count
3862380,2014-07-17 09:05:00+00:00,3524669,12.70,Erythrocyte distribution width [Ratio] by Auto...
14656557,2011-07-17 09:07:00+00:00,3524669,140.00,Sodium [Moles/volume] in Serum or Plasma
13202728,2015-07-17 12:05:00+00:00,3524669,12.40,Cancer Ag 15-3 [Units/volume] in Serum or Plasma
36693262,2019-07-17 09:02:00+00:00,3524669,5.60,Monocytes/100 leukocytes in Blood by Automated...
18166537,2019-07-17 09:04:00+00:00,3524669,11.80,Hemoglobin [Mass/volume] in Blood
3618914,2011-07-17 09:10:00+00:00,3524669,27.00,Lymphocytes/100 leukocytes in Blood by Automat...
3862349,2018-07-17 09:05:00+00:00,3524669,13.20,Erythrocyte distribution width [Ratio] by Auto...
19709331,2015-07-17 13:09:00+00:00,3524669,5.60,Leukocytes [#/volume] in Blood by Automated count
14459348,2018-07-17 12:10:00+00:00,3524669,10.00,Calcium [Mass/volume] in Serum or Plasma
40792265,2018-07-17 09:11:00+00:00,3524669,0.30,Basophils/100 leukocytes in Blood by Automated...
24694992,2018-07-17 09:06:00+00:00,3524669,10.70,Platelet mean volume [Entitic volume] in Blood...
31683244,2019-07-17 13:01:00+00:00,3524669,4.80,Potassium [Moles/volume] in Serum or Plasma
37797907,2014-07-17 11:10:00+00:00,3524669,3.60,Globulin [Mass/volume] in Serum by calculation
24475418,2019-07-17 10:03:00+00:00,3524669,24.00,"Carbon dioxide, total [Moles/volume] in Serum ..."
27645306,2013-07-17 03:08:00+00:00,3524669,30.00,Urea nitrogen [Mass/volume] in Serum or Plasma
3546015,2018-07-17 09:02:00+00:00,3524669,2.40,Eosinophils/100 leukocytes in Blood by Automat...
3618897,2018-07-17 09:02:00+00:00,3524669,17.90,Lymphocytes/100 leukocytes in Blood by Automat...
39904124,2017-07-17 10:07:00+00:00,3524669,2.10,Creatinine [Mass/volume] in Serum or Plasma
8142185,2011-07-17 09:07:00+00:00,3524669,80.00,Alkaline phosphatase [Enzymatic activity/volum...
26887082,2010-07-17 02:05:00+00:00,3524669,9.80,Calcium [Mass/volume] in Serum or Plasma
3546067,2017-07-17 09:07:00+00:00,3524669,6.90,Eosinophils/100 leukocytes in Blood by Automat...
8900113,2014-07-17 13:10:00+00:00,3524669,7.90,Urate [Mass/volume] in Serum or Plasma
9885705,2017-07-17 09:10:00+00:00,3524669,11.10,Hemoglobin [Mass/volume] in Blood
35464233,2013-07-17 04:05:00+00:00,3524669,140.00,Sodium [Moles/volume] in Serum or Plasma

In [11]:
measurement_df['standard_concept_name'].str.contains('blood', regex=False).nunique

<bound method IndexOpsMixin.nunique of 0           False
1           False
2           False
3           False
4           False
            ...
41504273    False
41504274    False
41504275    False
41504276    False
41504277    False
Name: standard_concept_name, Length: 41504278, dtype: bool>

In [2]:

person_co=pd.merge(person_df,
                   condition_df,
                   on='person_id', how='inner')

In [ ]:
person_co_mr=pd.merge(person_co, 
                               measurement_df,
                               on='person_id', how='inner')

In [ ]:
person_co_mr_dr=pd.merge(person_co_mr, 
                               drug_df,
                               on='person_id', how='left')

In [ ]:
person_co_dr_mr_svy=pd.merge(person_co_mr_dr,
                             survey_df,
                             on='person_id', how='left')

In [ ]:
person_co_dr_mr_svy_obs=pd.merge(person_co_dr_mr_svy,
                             observation_df,
                             on='person_id', how='left')

In [ ]:
person_co_dr_mr_svy_obs.sort_values('person_id').head(60)

# saving to workspace in google bucket

In [ ]:
# This snippet assumes you run setup first

# This code saves your dataframe into a csv file in a "data" folder in Google Bucket

# Replace df with THE NAME OF YOUR DATAFRAME
my_dataframe = person_co_dr_mr_svy_obs   

# Replace 'test.csv' with THE NAME of the file you're going to store in the bucket (don't delete the quotation marks)
destination_filename = 'person_cond_drug_mearsu_svy_obs.csv'

########################################################################
##
################# DON'T CHANGE FROM HERE ###############################
##
########################################################################

# save dataframe in a csv file in the same workspace as the notebook
my_dataframe.to_csv(destination_filename, index=False)

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file to the bucket
os.system(f"gsutil cp './{destination_filename}' '{my_bucket}/data/'")
print(f'[INFO] {destination_filename} is successfully uploaded in your bucket.')